export const BULK_SIM_DEFAULT_TOP_RESULTS = 5;

export const BULK_SIM_MIN_COMBINATIONS = 20;

export const BULK_SIM_CULLING_COEFFICIENT = 1.35;

export const BULK_SIM_COMBINATION_LOG_MIN = 10;

export const BULK_SIM_MAX_ADAPTIVE_PASSES = 2;

export const BULK_SIM_ADAPTIVE_MAX_ITERATION_MULTIPLIER = 4;

export const BULK_SIM_SURVIVOR_SOFT_CAP_MULTIPLIER = 2;

export const BULK_SIM_LOW_STAGE_SURVIVOR_SCALE_REFERENCE = 1000;

export const BULK_SIM_MEDIUM_STAGE_SURVIVOR_SCALE_REFERENCE = 100;
