import { Spec } from '../proto/common';

export const CHARACTER_LEVEL = 70;
export const BOSS_LEVEL = CHARACTER_LEVEL + 3;

export const PHYSICAL_HASTE_RATING_PER_HASTE_PERCENT = 425.0;
export const SPELL_HASTE_RATING_PER_HASTE_PERCENT = 425.0;
export const EXPERTISE_PER_QUARTER_PERCENT_REDUCTION = 85.0;
export const SPELL_CRIT_RATING_PER_CRIT_PERCENT = 600.0;
export const PHYSICAL_CRIT_RATING_PER_CRIT_PERCENT = 600.0;
export const SPELL_HIT_RATING_PER_HIT_PERCENT = 340.0;
export const PHYSICAL_HIT_RATING_PER_HIT_PERCENT = 340.0;
export const DODGE_RATING_PER_DODGE_PERCENT = 885.0;
export const PARRY_RATING_PER_PARRY_PERCENT = 885.0;
