export const CHARACTER_LEVEL = 70;
export const BOSS_LEVEL = CHARACTER_LEVEL + 3;

export const EXPERTISE_PER_QUARTER_PERCENT_REDUCTION = 3.942308;
export const PHYSICAL_HASTE_RATING_PER_HASTE_PERCENT = 15.769233;
export const SPELL_HASTE_RATING_PER_HASTE_PERCENT = 15.769233;
export const SPELL_CRIT_RATING_PER_CRIT_PERCENT = 22.076923;
export const PHYSICAL_CRIT_RATING_PER_CRIT_PERCENT = 22.076923;
export const SPELL_HIT_RATING_PER_HIT_PERCENT = 12.615385;
export const PHYSICAL_HIT_RATING_PER_HIT_PERCENT = 15.769233;
export const DODGE_RATING_PER_DODGE_PERCENT = 18.923079;
export const PARRY_RATING_PER_PARRY_PERCENT = 23.653847;
export const DEFENSE_RATING_PER_DEFENSE_LEVEL = 2.365385;
export const BLOCK_RATING_PER_BLOCK_PERCENT = 7.884615;

export const MISS_DODGE_PARRY_BLOCK_CRIT_CHANCE_PER_DEFENSE = 0.04;
export const RESILIENCE_RATING_PER_CRIT_REDUCTION_CHANCE = 39.4231;
export const DEFENSE_RATING_TO_CHANCE_REDUCTION = (1.0 / DEFENSE_RATING_PER_DEFENSE_LEVEL) * MISS_DODGE_PARRY_BLOCK_CRIT_CHANCE_PER_DEFENSE;
