package paladin

import (
	"time"

	"github.com/wowsims/tbc/sim/core"
)

func (paladin *Paladin) registerBlessings() {
	paladin.registerBlessingOfMight()
	paladin.registerBlessingOfWisdom()
	paladin.registerBlessingOfSalvation()
	paladin.registerBlessingOfProtection()

	// Talent blessings
	if paladin.Talents.BlessingOfKings {
		paladin.registerBlessingOfKings()
	}
	if paladin.Talents.BlessingOfSanctuary {
		paladin.registerBlessingOfSanctuary()
	}
}

// Blessing of Might
// https://www.wowhead.com/tbc/spell=27141
//
// Places a Blessing on the friendly target, increasing attack power for 10 min.
// Players may only have one Blessing on them per Paladin at any one time.
func (paladin *Paladin) registerBlessingOfMight() {
	actionID := core.ActionID{SpellID: 27141}

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    core.SpellSchoolHoly,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskBlessingOfMight,

		DamageMultiplier: 1,
		ThreatMultiplier: 1,

		ManaCost: core.ManaCostOptions{
			FlatCost: 180, // Rank 8
		},
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: core.GCDDefault,
			},
		},

		ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
			// TODO: Implement blessing application
		},
	})
}

// Blessing of Wisdom
// https://www.wowhead.com/tbc/spell=27142
//
// Places a Blessing on the friendly target, restoring mana every 5 seconds for 10 min.
// Players may only have one Blessing on them per Paladin at any one time.
func (paladin *Paladin) registerBlessingOfWisdom() {
	actionID := core.ActionID{SpellID: 27142}

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    core.SpellSchoolHoly,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskBlessingOfWisdom,

		DamageMultiplier: 1,
		ThreatMultiplier: 1,

		ManaCost: core.ManaCostOptions{
			FlatCost: 165, // Rank 7
		},
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: core.GCDDefault,
			},
		},

		ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
			// TODO: Implement blessing application
		},
	})
}

// Blessing of Kings (Talent)
// https://www.wowhead.com/tbc/spell=25898
//
// Places a Blessing on the friendly target, increasing total stats by 10% for 10 min.
// Players may only have one Blessing on them per Paladin at any one time.
func (paladin *Paladin) registerBlessingOfKings() {
	actionID := core.ActionID{SpellID: 25898}

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    core.SpellSchoolHoly,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskBlessingOfKings,

		DamageMultiplier: 1,
		ThreatMultiplier: 1,

		ManaCost: core.ManaCostOptions{
			BaseCostPercent: 6,
		},
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: core.GCDDefault,
			},
		},

		ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
			// TODO: Implement blessing application
		},
	})
}

// Blessing of Salvation
// https://www.wowhead.com/tbc/spell=1038
//
// Places a Blessing on the friendly target, reducing the amount of threat
// generated by the target by 30% for 10 min. Players may only have one
// Blessing on them per Paladin at any one time.
func (paladin *Paladin) registerBlessingOfSalvation() {
	actionID := core.ActionID{SpellID: 1038}

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    core.SpellSchoolHoly,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskBlessingOfSalvation,

		DamageMultiplier: 1,
		ThreatMultiplier: 1,

		ManaCost: core.ManaCostOptions{
			BaseCostPercent: 6,
		},
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: core.GCDDefault,
			},
		},

		ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
			// TODO: Implement blessing application
		},
	})
}

// Blessing of Sanctuary (Talent)
// https://www.wowhead.com/tbc/spell=25899
//
// Places a Blessing on the friendly target, reducing damage taken from all sources
// by 3% for 10 min. In addition, when the target blocks, parries, or dodges a melee
// attack the target will gain 10 rage, 20 runic power, or 2% of maximum mana.
// Players may only have one Blessing on them per Paladin at any one time.
func (paladin *Paladin) registerBlessingOfSanctuary() {
	actionID := core.ActionID{SpellID: 25899}

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    core.SpellSchoolHoly,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskBlessingOfSanctuary,

		DamageMultiplier: 1,
		ThreatMultiplier: 1,

		ManaCost: core.ManaCostOptions{
			FlatCost: 135,
		},
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: core.GCDDefault,
			},
		},

		ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
			// TODO: Implement blessing application
		},
	})
}

// Blessing of Protection
// https://www.wowhead.com/tbc/spell=10278
//
// A targeted party member is protected from all physical attacks for 10 sec,
// but during that time they cannot attack or use physical abilities.
// Players may only have one Blessing on them per Paladin at any one time.
// Once protected, the target cannot be protected by another Hand of Protection
// for 1 min. Cannot be used on a target with Forbearance.
// Causes Forbearance for 1 min.
func (paladin *Paladin) registerBlessingOfProtection() {
	actionID := core.ActionID{SpellID: 10278}

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    core.SpellSchoolHoly,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskBlessingOfProtection,

		DamageMultiplier: 1,
		ThreatMultiplier: 1,

		ManaCost: core.ManaCostOptions{
			BaseCostPercent: 6,
		},
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: core.GCDDefault,
			},
			CD: core.Cooldown{
				Timer:    paladin.NewTimer(),
				Duration: time.Minute * 5,
			},
		},

		ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
			// TODO: Implement blessing application and forbearance
		},
	})
}
