package paladin

import (
	"github.com/wowsims/tbc/sim/common/shared"
	"github.com/wowsims/tbc/sim/core"
)

// Righteous Fury
// https://www.wowhead.com/tbc/spell=25780
//
// Increases the threat generated by your Holy spells by 60%.
// Improved Righteous Fury increases the threat bonus by 16/33/50% (i.e. 60% * 1.5 = 90% at rank 3).
func (paladin *Paladin) registerRighteousFury() {
	actionID := core.ActionID{SpellID: 25780}

	// Base RF = 60% threat, which Improved Righteous Fury raises by the talent's own per-rank
	// percentage: 16 / 33 / 50, so 69.6% / 79.8% / 90%.
	//
	// Named by aura rather than read out of Direct: the talent's other effect cuts damage taken,
	// and which of the two lands in Direct is the generator's choice, not a promise. MultiplierAt
	// answers 1 at rank 0, so an untaken talent leaves the base 60% alone.
	threatBonus := 0.6 * genRanks.ImprovedRighteousFury.
		Effect(shared.A_ADD_PCT_MODIFIER, shared.SPELLMOD_ALL_EFFECTS).
		MultiplierAt(paladin.Talents.ImprovedRighteousFury)

	rfAura := paladin.RegisterAura(core.Aura{
		Label:    "Righteous Fury",
		ActionID: actionID,
		Duration: core.NeverExpires,
	}).AttachSpellMod(core.SpellModConfig{
		Kind:       core.SpellMod_ThreatMultiplier_Pct,
		School:     core.SpellSchoolHoly,
		FloatValue: threatBonus,
	})

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    core.SpellSchoolHoly,
		DefenseType:    core.DefenseTypeMagic,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskRighteousFury,

		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: core.GCDDefault,
			},
		},

		ApplyEffects: func(sim *core.Simulation, _ *core.Unit, spell *core.Spell) {
			spell.RelatedSelfBuff.Activate(sim)
		},

		RelatedSelfBuff: rfAura,
	})
}
