// Code generated by tools/database/gen_db -gen=spellranks. DO NOT EDIT.

package paladin

import "github.com/wowsims/tbc/sim/common/shared"

type generatedRanks struct {
	Consecration   shared.RankTable
	HammerOfWrath  shared.RankTable
	HolyWrath      shared.RankTable
	Exorcism       shared.RankTable
	HolyLight      shared.RankTable
	FlashOfLight   shared.RankTable
	LayOnHands     shared.RankTable
	HolyShield     shared.RankTable
	HolyShock      shared.RankTable
	AvengersShield shared.RankTable
}

var genRanks = generatedRanks{
	Consecration: shared.RankTable{
		{Rank: 1, SpellID: 26573, Cost: 120, Periodic: &shared.Periodic{Tick: 8, Coef: 0.11900000274181366}},
		{Rank: 2, SpellID: 20116, Cost: 205, Periodic: &shared.Periodic{Tick: 15, Coef: 0.11900000274181366}},
		{Rank: 3, SpellID: 20922, Cost: 290, Periodic: &shared.Periodic{Tick: 24, Coef: 0.11900000274181366}},
		{Rank: 4, SpellID: 20923, Cost: 390, Periodic: &shared.Periodic{Tick: 35, Coef: 0.11900000274181366}},
		{Rank: 5, SpellID: 20924, Cost: 505, Periodic: &shared.Periodic{Tick: 48, Coef: 0.11900000274181366}},
		{Rank: 6, SpellID: 27173, Cost: 660, Periodic: &shared.Periodic{Tick: 64, Coef: 0.11900000274181366}},
	},
	HammerOfWrath: shared.RankTable{
		{Rank: 1, SpellID: 24275, Cost: 235, Direct: &shared.Amount{Min: 316, Max: 348, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 24274, Cost: 290, Direct: &shared.Amount{Min: 412, Max: 455, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 24239, Cost: 340, Direct: &shared.Amount{Min: 519, Max: 572, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 27180, Cost: 440, Direct: &shared.Amount{Min: 672, Max: 742, Coef: 0.42899999022483826}},
	},
	HolyWrath: shared.RankTable{
		{Rank: 1, SpellID: 2812, Cost: 550, Direct: &shared.Amount{Min: 368, Max: 435, Coef: 0.28600001335144043}},
		{Rank: 2, SpellID: 10318, Cost: 685, Direct: &shared.Amount{Min: 497, Max: 584, Coef: 0.28600001335144043}},
		{Rank: 3, SpellID: 27139, Cost: 825, Direct: &shared.Amount{Min: 637, Max: 748, Coef: 0.28600001335144043}},
	},
	Exorcism: shared.RankTable{
		{Rank: 1, SpellID: 879, Cost: 70, Direct: &shared.Amount{Min: 90, Max: 102, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 5614, Cost: 115, Direct: &shared.Amount{Min: 160, Max: 180, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 5615, Cost: 155, Direct: &shared.Amount{Min: 227, Max: 255, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 10312, Cost: 200, Direct: &shared.Amount{Min: 316, Max: 354, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 10313, Cost: 240, Direct: &shared.Amount{Min: 407, Max: 453, Coef: 0.42899999022483826}},
		{Rank: 6, SpellID: 10314, Cost: 295, Direct: &shared.Amount{Min: 521, Max: 579, Coef: 0.42899999022483826}},
		{Rank: 7, SpellID: 27138, Cost: 340, Direct: &shared.Amount{Min: 626, Max: 698, Coef: 0.42899999022483826}},
	},
	HolyLight: shared.RankTable{
		{Rank: 1, SpellID: 635, Cost: 35, Heal: &shared.Amount{Min: 42, Max: 51, Coef: 0.20499999821186066}},
		{Rank: 2, SpellID: 639, Cost: 60, Heal: &shared.Amount{Min: 81, Max: 96, Coef: 0.33899998664855957}},
		{Rank: 3, SpellID: 647, Cost: 110, Heal: &shared.Amount{Min: 167, Max: 196, Coef: 0.5540000200271606}},
		{Rank: 4, SpellID: 1026, Cost: 190, Heal: &shared.Amount{Min: 322, Max: 368, Coef: 0.7139999866485596}},
		{Rank: 5, SpellID: 1042, Cost: 275, Heal: &shared.Amount{Min: 506, Max: 569, Coef: 0.7139999866485596}},
		{Rank: 6, SpellID: 3472, Cost: 365, Heal: &shared.Amount{Min: 717, Max: 799, Coef: 0.7139999866485596}},
		{Rank: 7, SpellID: 10328, Cost: 465, Heal: &shared.Amount{Min: 968, Max: 1076, Coef: 0.7139999866485596}},
		{Rank: 8, SpellID: 10329, Cost: 580, Heal: &shared.Amount{Min: 1272, Max: 1414, Coef: 0.7139999866485596}},
		{Rank: 9, SpellID: 25292, Cost: 660, Heal: &shared.Amount{Min: 1619, Max: 1799, Coef: 0.7139999866485596}},
		{Rank: 10, SpellID: 27135, Cost: 710, Heal: &shared.Amount{Min: 1773, Max: 1971, Coef: 0.7139999866485596}},
		{Rank: 11, SpellID: 27136, Cost: 840, Heal: &shared.Amount{Min: 2196, Max: 2446, Coef: 0.7139999866485596}},
	},
	FlashOfLight: shared.RankTable{
		{Rank: 1, SpellID: 19750, Cost: 35, Heal: &shared.Amount{Min: 67, Max: 77, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 19939, Cost: 50, Heal: &shared.Amount{Min: 102, Max: 117, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 19940, Cost: 70, Heal: &shared.Amount{Min: 153, Max: 171, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 19941, Cost: 90, Heal: &shared.Amount{Min: 206, Max: 231, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 19942, Cost: 115, Heal: &shared.Amount{Min: 278, Max: 310, Coef: 0.42899999022483826}},
		{Rank: 6, SpellID: 19943, Cost: 140, Heal: &shared.Amount{Min: 356, Max: 396, Coef: 0.42899999022483826}},
		{Rank: 7, SpellID: 27137, Cost: 180, Heal: &shared.Amount{Min: 458, Max: 513, Coef: 0.42899999022483826}},
	},
	LayOnHands: shared.RankTable{
		{Rank: 1, SpellID: 633},
		{Rank: 2, SpellID: 2800, Energize: 250},
		{Rank: 3, SpellID: 10310, Energize: 550},
		{Rank: 4, SpellID: 27154, Energize: 900},
	},
	HolyShield: shared.RankTable{
		{Rank: 1, SpellID: 20925, Cost: 135, Direct: &shared.Amount{Min: 59, Max: 59, Coef: 0.05000000074505806}},
		{Rank: 2, SpellID: 20927, Cost: 175, Direct: &shared.Amount{Min: 86, Max: 86, Coef: 0.05000000074505806}},
		{Rank: 3, SpellID: 20928, Cost: 215, Direct: &shared.Amount{Min: 117, Max: 117, Coef: 0.05000000074505806}},
		{Rank: 4, SpellID: 27179, Cost: 280, Direct: &shared.Amount{Min: 155, Max: 155, Coef: 0.05000000074505806}},
	},
	HolyShock: shared.RankTable{
		{Rank: 1, SpellID: 20473, Cost: 335, Direct: &shared.Amount{Min: 277, Max: 299, Coef: 0.42899999022483826}, Heal: &shared.Amount{Min: 351, Max: 379, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 20929, Cost: 410, Direct: &shared.Amount{Min: 379, Max: 409, Coef: 0.42899999022483826}, Heal: &shared.Amount{Min: 480, Max: 518, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 20930, Cost: 485, Direct: &shared.Amount{Min: 496, Max: 536, Coef: 0.42899999022483826}, Heal: &shared.Amount{Min: 628, Max: 680, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 27174, Cost: 575, Direct: &shared.Amount{Min: 614, Max: 664, Coef: 0.42899999022483826}, Heal: &shared.Amount{Min: 777, Max: 841, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 33072, Cost: 650, Direct: &shared.Amount{Min: 721, Max: 779, Coef: 0.42899999022483826}, Heal: &shared.Amount{Min: 913, Max: 987, Coef: 0.42899999022483826}},
	},
	AvengersShield: shared.RankTable{
		{Rank: 1, SpellID: 31935, Cost: 500, Direct: &shared.Amount{Min: 270, Max: 330, Coef: 0.19300000369548798}},
		{Rank: 2, SpellID: 32699, Cost: 615, Direct: &shared.Amount{Min: 370, Max: 452, Coef: 0.19300000369548798}},
		{Rank: 3, SpellID: 32700, Cost: 780, Direct: &shared.Amount{Min: 494, Max: 602, Coef: 0.19300000369548798}},
	},
}
