// Code generated by tools/database/gen_spellranks. DO NOT EDIT.

package paladin

import (
	"time"

	"github.com/wowsims/tbc/sim/common/shared"
)

// Not generated:
//   Eye for an Eye: rank 1 is ambiguous between spells 25997, 9799
//   Judgement of Command: rank 1 is ambiguous between spells 20425, 20467
//   Seal of Righteousness: rank 1 is ambiguous between spells 20154, 21084
//   Vindication: rank 1 is ambiguous between spells 67, 9452

type generatedRanks struct {
	Anticipation                  shared.SpellRankTable
	ArdentDefender                shared.SpellRankTable
	AvengersShield                shared.SpellRankTable
	Benediction                   shared.SpellRankTable
	BlessedLife                   shared.SpellRankTable
	BlessingOfLight               shared.SpellRankTable
	BlessingOfMight               shared.SpellRankTable
	BlessingOfProtection          shared.SpellRankTable
	BlessingOfSacrifice           shared.SpellRankTable
	BlessingOfSanctuary           shared.SpellRankTable
	BlessingOfWisdom              shared.SpellRankTable
	BloodCorruption               shared.SpellRankTable
	CombatExpertise               shared.SpellRankTable
	Consecration                  shared.SpellRankTable
	Conviction                    shared.SpellRankTable
	Crusade                       shared.SpellRankTable
	Deflection                    shared.SpellRankTable
	DevotionAura                  shared.SpellRankTable
	DivineProtection              shared.SpellRankTable
	DivinePurpose                 shared.SpellRankTable
	DivineShield                  shared.SpellRankTable
	Exorcism                      shared.SpellRankTable
	Fanaticism                    shared.SpellRankTable
	FireResistanceAura            shared.SpellRankTable
	FlashOfLight                  shared.SpellRankTable
	FrostResistanceAura           shared.SpellRankTable
	GreaterBlessingOfLight        shared.SpellRankTable
	GreaterBlessingOfMight        shared.SpellRankTable
	GreaterBlessingOfSanctuary    shared.SpellRankTable
	GreaterBlessingOfWisdom       shared.SpellRankTable
	GuardiansFavor                shared.SpellRankTable
	HammerOfJustice               shared.SpellRankTable
	HammerOfWrath                 shared.SpellRankTable
	HolyGuidance                  shared.SpellRankTable
	HolyLight                     shared.SpellRankTable
	HolyPower                     shared.SpellRankTable
	HolyShield                    shared.SpellRankTable
	HolyShock                     shared.SpellRankTable
	HolyVengeance                 shared.SpellRankTable
	HolyWrath                     shared.SpellRankTable
	ImprovedBlessingOfMight       shared.SpellRankTable
	ImprovedConcentrationAura     shared.SpellRankTable
	ImprovedDevotionAura          shared.SpellRankTable
	ImprovedHammerOfJustice       shared.SpellRankTable
	ImprovedHolyShield            shared.SpellRankTable
	ImprovedJudgement             shared.SpellRankTable
	ImprovedRetributionAura       shared.SpellRankTable
	ImprovedRighteousFury         shared.SpellRankTable
	ImprovedSanctityAura          shared.SpellRankTable
	ImprovedSealOfTheCrusader     shared.SpellRankTable
	JudgementOfBlood              shared.SpellRankTable
	JudgementOfCorruption         shared.SpellRankTable
	JudgementOfJustice            shared.SpellRankTable
	JudgementOfLight              shared.SpellRankTable
	JudgementOfRighteousness      shared.SpellRankTable
	JudgementOfVengeance          shared.SpellRankTable
	JudgementOfWisdom             shared.SpellRankTable
	JudgementOfTheCrusader        shared.SpellRankTable
	LayOnHands                    shared.SpellRankTable
	LightsGrace                   shared.SpellRankTable
	OneHandedWeaponSpecialization shared.SpellRankTable
	Precision                     shared.SpellRankTable
	PureOfHeart                   shared.SpellRankTable
	PurifyingPower                shared.SpellRankTable
	PursuitOfJustice              shared.SpellRankTable
	Reckoning                     shared.SpellRankTable
	Redemption                    shared.SpellRankTable
	Redoubt                       shared.SpellRankTable
	RetributionAura               shared.SpellRankTable
	SacredDuty                    shared.SpellRankTable
	SanctifiedJudgement           shared.SpellRankTable
	SanctifiedLight               shared.SpellRankTable
	SanctifiedSeals               shared.SpellRankTable
	SealOfBlood                   shared.SpellRankTable
	SealOfCommand                 shared.SpellRankTable
	SealOfCorruption              shared.SpellRankTable
	SealOfJustice                 shared.SpellRankTable
	SealOfLight                   shared.SpellRankTable
	SealOfVengeance               shared.SpellRankTable
	SealOfWisdom                  shared.SpellRankTable
	SealOfTheCrusader             shared.SpellRankTable
	SealOfTheMartyr               shared.SpellRankTable
	ShadowResistanceAura          shared.SpellRankTable
	ShieldSpecialization          shared.SpellRankTable
	SpellWarding                  shared.SpellRankTable
	SpiritualAttunement           shared.SpellRankTable
	Stoicism                      shared.SpellRankTable
	Toughness                     shared.SpellRankTable
	TurnEvil                      shared.SpellRankTable
	TurnUndead                    shared.SpellRankTable
	TwoHandedWeaponSpecialization shared.SpellRankTable
	UnyieldingFaith               shared.SpellRankTable
	Vengeance                     shared.SpellRankTable
}

var genRanks = generatedRanks{
	Anticipation: shared.SpellRankTable{
		{Rank: 1, SpellID: 20096, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 2, SpellID: 20097, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 3, SpellID: 20098, Direct: shared.SpellRankFlat{Value: 12, Coef: 0}},
		{Rank: 4, SpellID: 20099, Direct: shared.SpellRankFlat{Value: 16, Coef: 0}},
		{Rank: 5, SpellID: 20100, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
	},
	ArdentDefender: shared.SpellRankTable{
		{Rank: 1, SpellID: 31850},
		{Rank: 2, SpellID: 31851},
		{Rank: 3, SpellID: 31852},
		{Rank: 4, SpellID: 31853},
		{Rank: 5, SpellID: 31854},
	},
	AvengersShield: shared.SpellRankTable{
		{Rank: 1, SpellID: 31935, Cost: 500, CastTime: 1000 * time.Millisecond, GCD: 1000 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 30, MissileSpeed: 35, Direct: shared.SpellRankRange{Min: 270, Max: 330, Coef: 0.19300000369548798}},
		{Rank: 2, SpellID: 32699, Cost: 615, CastTime: 1000 * time.Millisecond, GCD: 1000 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 30, MissileSpeed: 35, Direct: shared.SpellRankRange{Min: 370, Max: 452, Coef: 0.19300000369548798}},
		{Rank: 3, SpellID: 32700, Cost: 780, CastTime: 1000 * time.Millisecond, GCD: 1000 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 30, MissileSpeed: 35, Direct: shared.SpellRankRange{Min: 494, Max: 602, Coef: 0.19300000369548798}},
	},
	Benediction: shared.SpellRankTable{
		{Rank: 1, SpellID: 20101},
		{Rank: 2, SpellID: 20102},
		{Rank: 3, SpellID: 20103},
		{Rank: 4, SpellID: 20104},
		{Rank: 5, SpellID: 20105},
	},
	BlessedLife: shared.SpellRankTable{
		{Rank: 1, SpellID: 31828},
		{Rank: 2, SpellID: 31829},
		{Rank: 3, SpellID: 31830},
	},
	BlessingOfLight: shared.SpellRankTable{
		{Rank: 1, SpellID: 19977, Cost: 85, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 210, Coef: 0}},
		{Rank: 2, SpellID: 19978, Cost: 110, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 300, Coef: 0}},
		{Rank: 3, SpellID: 19979, Cost: 135, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 400, Coef: 0}},
		{Rank: 4, SpellID: 27144, Cost: 180, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 580, Coef: 0}},
	},
	BlessingOfMight: shared.SpellRankTable{
		{Rank: 1, SpellID: 19740, Cost: 20, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 2, SpellID: 19834, Cost: 30, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
		{Rank: 3, SpellID: 19835, Cost: 45, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 55, Coef: 0}},
		{Rank: 4, SpellID: 19836, Cost: 60, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 85, Coef: 0}},
		{Rank: 5, SpellID: 19837, Cost: 85, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 115, Coef: 0}},
		{Rank: 6, SpellID: 19838, Cost: 110, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 155, Coef: 0}},
		{Rank: 7, SpellID: 25291, Cost: 130, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 185, Coef: 0}},
		{Rank: 8, SpellID: 27140, Cost: 145, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 220, Coef: 0}},
	},
	BlessingOfProtection: shared.SpellRankTable{
		{Rank: 1, SpellID: 1022, Cost: 25, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond, MaxRange: 30},
		{Rank: 2, SpellID: 5599, Cost: 45, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond, MaxRange: 30},
		{Rank: 3, SpellID: 10278, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond, MaxRange: 30},
	},
	BlessingOfSacrifice: shared.SpellRankTable{
		{Rank: 1, SpellID: 6940, Cost: 80, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 45, Coef: 0}},
		{Rank: 2, SpellID: 20729, Cost: 100, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 55, Coef: 0}},
		{Rank: 3, SpellID: 27147, Cost: 115, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 81, Coef: 0}},
		{Rank: 4, SpellID: 27148, Cost: 135, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 104, Coef: 0}},
	},
	BlessingOfSanctuary: shared.SpellRankTable{
		{Rank: 1, SpellID: 20911, Cost: 60, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 14, Coef: 0}},
		{Rank: 2, SpellID: 20912, Cost: 85, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 21, Coef: 0}},
		{Rank: 3, SpellID: 20913, Cost: 110, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 28, Coef: 0}},
		{Rank: 4, SpellID: 20914, Cost: 135, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
		{Rank: 5, SpellID: 27168, Cost: 180, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 46, Coef: 0}},
	},
	BlessingOfWisdom: shared.SpellRankTable{
		{Rank: 1, SpellID: 19742, Cost: 30, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 19850, Cost: 45, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 3, SpellID: 19852, Cost: 65, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 4, SpellID: 19853, Cost: 90, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 5, SpellID: 19854, Cost: 115, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 6, SpellID: 25290, Cost: 125, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 33, Coef: 0}},
		{Rank: 7, SpellID: 27142, Cost: 150, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 41, Coef: 0}},
	},
	BloodCorruption: shared.SpellRankTable{
		{Rank: 1, SpellID: 356110, MaxRange: 100, Periodic: shared.SpellRankPeriodic{Tick: 30, Coef: 0.03400000184774399, TickLength: 3000 * time.Millisecond, NumberOfTicks: 5}},
	},
	CombatExpertise: shared.SpellRankTable{
		{Rank: 1, SpellID: 31858, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 31859, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 31860, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 31861, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 31862, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	Consecration: shared.SpellRankTable{
		{Rank: 1, SpellID: 26573, Cost: 120, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, Periodic: shared.SpellRankPeriodic{Tick: 8, Coef: 0.11900000274181366, TickLength: 1000 * time.Millisecond, NumberOfTicks: 8}},
		{Rank: 2, SpellID: 20116, Cost: 205, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, Periodic: shared.SpellRankPeriodic{Tick: 15, Coef: 0.11900000274181366, TickLength: 1000 * time.Millisecond, NumberOfTicks: 8}},
		{Rank: 3, SpellID: 20922, Cost: 290, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, Periodic: shared.SpellRankPeriodic{Tick: 24, Coef: 0.11900000274181366, TickLength: 1000 * time.Millisecond, NumberOfTicks: 8}},
		{Rank: 4, SpellID: 20923, Cost: 390, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, Periodic: shared.SpellRankPeriodic{Tick: 35, Coef: 0.11900000274181366, TickLength: 1000 * time.Millisecond, NumberOfTicks: 8}},
		{Rank: 5, SpellID: 20924, Cost: 505, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, Periodic: shared.SpellRankPeriodic{Tick: 48, Coef: 0.11900000274181366, TickLength: 1000 * time.Millisecond, NumberOfTicks: 8}},
		{Rank: 6, SpellID: 27173, Cost: 660, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, Periodic: shared.SpellRankPeriodic{Tick: 64, Coef: 0.11900000274181366, TickLength: 1000 * time.Millisecond, NumberOfTicks: 8}},
	},
	Conviction: shared.SpellRankTable{
		{Rank: 1, SpellID: 20117},
		{Rank: 2, SpellID: 20118, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 20119, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 20120, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 20121, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	Crusade: shared.SpellRankTable{
		{Rank: 1, SpellID: 31866},
		{Rank: 2, SpellID: 31867, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 31868, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
	},
	Deflection: shared.SpellRankTable{
		{Rank: 1, SpellID: 20060},
		{Rank: 2, SpellID: 20061, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 20062, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
		{Rank: 4, SpellID: 20063, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 5, SpellID: 20064, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
	},
	DevotionAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 465, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 55, Coef: 0}},
		{Rank: 2, SpellID: 10290, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 160, Coef: 0}},
		{Rank: 3, SpellID: 643, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 275, Coef: 0}},
		{Rank: 4, SpellID: 10291, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 390, Coef: 0}},
		{Rank: 5, SpellID: 1032, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 505, Coef: 0}},
		{Rank: 6, SpellID: 10292, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 620, Coef: 0}},
		{Rank: 7, SpellID: 10293, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 735, Coef: 0}},
		{Rank: 8, SpellID: 27149, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 861, Coef: 0}},
	},
	DivineProtection: shared.SpellRankTable{
		{Rank: 1, SpellID: 498, Cost: 15, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond},
		{Rank: 2, SpellID: 5573, Cost: 35, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond},
	},
	DivinePurpose: shared.SpellRankTable{
		{Rank: 1, SpellID: 31871},
		{Rank: 2, SpellID: 31872},
		{Rank: 3, SpellID: 31873},
	},
	DivineShield: shared.SpellRankTable{
		{Rank: 1, SpellID: 642, Cost: 75, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond},
		{Rank: 2, SpellID: 1020, Cost: 110, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond},
	},
	Exorcism: shared.SpellRankTable{
		{Rank: 1, SpellID: 879, Cost: 70, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 90, Max: 102, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 5614, Cost: 115, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 160, Max: 180, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 5615, Cost: 155, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 227, Max: 255, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 10312, Cost: 200, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 316, Max: 354, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 10313, Cost: 240, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 407, Max: 453, Coef: 0.42899999022483826}},
		{Rank: 6, SpellID: 10314, Cost: 295, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 521, Max: 579, Coef: 0.42899999022483826}},
		{Rank: 7, SpellID: 27138, Cost: 340, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 626, Max: 698, Coef: 0.42899999022483826}},
	},
	Fanaticism: shared.SpellRankTable{
		{Rank: 1, SpellID: 31879, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
		{Rank: 2, SpellID: 31880, Direct: shared.SpellRankFlat{Value: 6, Coef: 1}},
		{Rank: 3, SpellID: 31881, Direct: shared.SpellRankFlat{Value: 9, Coef: 1}},
		{Rank: 4, SpellID: 31882, Direct: shared.SpellRankFlat{Value: 12, Coef: 1}},
		{Rank: 5, SpellID: 31883, Direct: shared.SpellRankFlat{Value: 15, Coef: 1}},
	},
	FireResistanceAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 19891, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 19899, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 45, Coef: 0}},
		{Rank: 3, SpellID: 19900, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 60, Coef: 0}},
		{Rank: 4, SpellID: 27153, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 70, Coef: 0}},
	},
	FlashOfLight: shared.SpellRankTable{
		{Rank: 1, SpellID: 19750, Cost: 35, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 67, Max: 77, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 19939, Cost: 50, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 102, Max: 117, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 19940, Cost: 70, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 153, Max: 171, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 19941, Cost: 90, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 206, Max: 231, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 19942, Cost: 115, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 278, Max: 310, Coef: 0.42899999022483826}},
		{Rank: 6, SpellID: 19943, Cost: 140, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 356, Max: 396, Coef: 0.42899999022483826}},
		{Rank: 7, SpellID: 27137, Cost: 180, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 458, Max: 513, Coef: 0.42899999022483826}},
	},
	FrostResistanceAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 19888, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 19897, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 45, Coef: 0}},
		{Rank: 3, SpellID: 19898, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 60, Coef: 0}},
		{Rank: 4, SpellID: 27152, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 70, Coef: 0}},
	},
	GreaterBlessingOfLight: shared.SpellRankTable{
		{Rank: 1, SpellID: 25890, Cost: 260, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 400, Coef: 0}},
		{Rank: 2, SpellID: 27145, Cost: 360, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 580, Coef: 0}},
	},
	GreaterBlessingOfMight: shared.SpellRankTable{
		{Rank: 1, SpellID: 25782, Cost: 220, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 155, Coef: 1}},
		{Rank: 2, SpellID: 25916, Cost: 260, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 185, Coef: 1}},
		{Rank: 3, SpellID: 27141, Cost: 295, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 220, Coef: 1}},
	},
	GreaterBlessingOfSanctuary: shared.SpellRankTable{
		{Rank: 1, SpellID: 25899, Cost: 270, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
		{Rank: 2, SpellID: 27169, Cost: 360, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 46, Coef: 0}},
	},
	GreaterBlessingOfWisdom: shared.SpellRankTable{
		{Rank: 1, SpellID: 25894, Cost: 230, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 25918, Cost: 250, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 33, Coef: 0}},
		{Rank: 3, SpellID: 27143, Cost: 310, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 41, Coef: 0}},
	},
	GuardiansFavor: shared.SpellRankTable{
		{Rank: 1, SpellID: 20174, Direct: shared.SpellRankFlat{Value: 2000, Coef: 1}},
		{Rank: 2, SpellID: 20175, Direct: shared.SpellRankFlat{Value: 4000, Coef: 1}},
	},
	HammerOfJustice: shared.SpellRankTable{
		{Rank: 1, SpellID: 853, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 60000 * time.Millisecond, MaxRange: 10},
		{Rank: 2, SpellID: 5588, Cost: 50, GCD: 1500 * time.Millisecond, Cooldown: 60000 * time.Millisecond, MaxRange: 10},
		{Rank: 3, SpellID: 5589, Cost: 75, GCD: 1500 * time.Millisecond, Cooldown: 60000 * time.Millisecond, MaxRange: 10},
		{Rank: 4, SpellID: 10308, Cost: 100, GCD: 1500 * time.Millisecond, Cooldown: 60000 * time.Millisecond, MaxRange: 10},
	},
	HammerOfWrath: shared.SpellRankTable{
		{Rank: 1, SpellID: 24275, Cost: 235, CastTime: 500 * time.Millisecond, GCD: 500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 30, MissileSpeed: 35, Direct: shared.SpellRankRange{Min: 316, Max: 348, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 24274, Cost: 290, CastTime: 500 * time.Millisecond, GCD: 500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 30, MissileSpeed: 35, Direct: shared.SpellRankRange{Min: 412, Max: 455, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 24239, Cost: 340, CastTime: 500 * time.Millisecond, GCD: 500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 30, MissileSpeed: 35, Direct: shared.SpellRankRange{Min: 519, Max: 572, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 27180, Cost: 440, CastTime: 500 * time.Millisecond, GCD: 500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 30, MissileSpeed: 35, Direct: shared.SpellRankRange{Min: 672, Max: 742, Coef: 0.42899999022483826}},
	},
	HolyGuidance: shared.SpellRankTable{
		{Rank: 1, SpellID: 31837, Direct: shared.SpellRankFlat{Value: 7, Coef: 0}},
		{Rank: 2, SpellID: 31838, Direct: shared.SpellRankFlat{Value: 14, Coef: 0}},
		{Rank: 3, SpellID: 31839, Direct: shared.SpellRankFlat{Value: 21, Coef: 0}},
		{Rank: 4, SpellID: 31840, Direct: shared.SpellRankFlat{Value: 28, Coef: 0}},
		{Rank: 5, SpellID: 31841, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
	},
	HolyLight: shared.SpellRankTable{
		{Rank: 1, SpellID: 635, Cost: 35, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 42, Max: 51, Coef: 0.20499999821186066}},
		{Rank: 2, SpellID: 639, Cost: 60, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 81, Max: 96, Coef: 0.33899998664855957}},
		{Rank: 3, SpellID: 647, Cost: 110, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 167, Max: 196, Coef: 0.5540000200271606}},
		{Rank: 4, SpellID: 1026, Cost: 190, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 322, Max: 368, Coef: 0.7139999866485596}},
		{Rank: 5, SpellID: 1042, Cost: 275, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 506, Max: 569, Coef: 0.7139999866485596}},
		{Rank: 6, SpellID: 3472, Cost: 365, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 717, Max: 799, Coef: 0.7139999866485596}},
		{Rank: 7, SpellID: 10328, Cost: 465, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 968, Max: 1076, Coef: 0.7139999866485596}},
		{Rank: 8, SpellID: 10329, Cost: 580, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 1272, Max: 1414, Coef: 0.7139999866485596}},
		{Rank: 9, SpellID: 25292, Cost: 660, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 1619, Max: 1799, Coef: 0.7139999866485596}},
		{Rank: 10, SpellID: 27135, Cost: 710, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 1773, Max: 1971, Coef: 0.7139999866485596}},
		{Rank: 11, SpellID: 27136, Cost: 840, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 40, Heal: shared.SpellRankRange{Min: 2196, Max: 2446, Coef: 0.7139999866485596}},
	},
	HolyPower: shared.SpellRankTable{
		{Rank: 1, SpellID: 5923},
		{Rank: 2, SpellID: 5924, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 5925, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
		{Rank: 4, SpellID: 5926, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 5, SpellID: 25829, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
	},
	HolyShield: shared.SpellRankTable{
		{Rank: 1, SpellID: 20925, Cost: 135, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 59, Coef: 0.05000000074505806}},
		{Rank: 2, SpellID: 20927, Cost: 175, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 86, Coef: 0.05000000074505806}},
		{Rank: 3, SpellID: 20928, Cost: 215, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 117, Coef: 0.05000000074505806}},
		{Rank: 4, SpellID: 27179, Cost: 280, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 155, Coef: 0.05000000074505806}},
	},
	HolyShock: shared.SpellRankTable{
		{Rank: 1, SpellID: 20473, Cost: 335, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 277, Max: 299, Coef: 0.42899999022483826}, Heal: shared.SpellRankRange{Min: 351, Max: 379, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 20929, Cost: 410, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 379, Max: 409, Coef: 0.42899999022483826}, Heal: shared.SpellRankRange{Min: 480, Max: 518, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 20930, Cost: 485, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 496, Max: 536, Coef: 0.42899999022483826}, Heal: shared.SpellRankRange{Min: 628, Max: 680, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 27174, Cost: 575, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 614, Max: 664, Coef: 0.42899999022483826}, Heal: shared.SpellRankRange{Min: 777, Max: 841, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 33072, Cost: 650, GCD: 1500 * time.Millisecond, Cooldown: 15000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 721, Max: 779, Coef: 0.42899999022483826}, Heal: shared.SpellRankRange{Min: 913, Max: 987, Coef: 0.42899999022483826}},
	},
	HolyVengeance: shared.SpellRankTable{
		{Rank: 1, SpellID: 31803, MaxRange: 100, Periodic: shared.SpellRankPeriodic{Tick: 30, Coef: 0.03400000184774399, TickLength: 3000 * time.Millisecond, NumberOfTicks: 5}},
	},
	HolyWrath: shared.SpellRankTable{
		{Rank: 1, SpellID: 2812, Cost: 550, CastTime: 2000 * time.Millisecond, GCD: 1500 * time.Millisecond, Cooldown: 60000 * time.Millisecond, MissileSpeed: 20, Direct: shared.SpellRankRange{Min: 368, Max: 435, Coef: 0.28600001335144043}},
		{Rank: 2, SpellID: 10318, Cost: 685, CastTime: 2000 * time.Millisecond, GCD: 1500 * time.Millisecond, Cooldown: 60000 * time.Millisecond, MissileSpeed: 20, Direct: shared.SpellRankRange{Min: 497, Max: 584, Coef: 0.28600001335144043}},
		{Rank: 3, SpellID: 27139, Cost: 825, CastTime: 2000 * time.Millisecond, GCD: 1500 * time.Millisecond, Cooldown: 60000 * time.Millisecond, MissileSpeed: 20, Direct: shared.SpellRankRange{Min: 637, Max: 748, Coef: 0.28600001335144043}},
	},
	ImprovedBlessingOfMight: shared.SpellRankTable{
		{Rank: 1, SpellID: 20042, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 2, SpellID: 20045, Direct: shared.SpellRankFlat{Value: 8, Coef: 1}},
		{Rank: 3, SpellID: 20046, Direct: shared.SpellRankFlat{Value: 12, Coef: 1}},
		{Rank: 4, SpellID: 20047, Direct: shared.SpellRankFlat{Value: 16, Coef: 1}},
		{Rank: 5, SpellID: 20048, Direct: shared.SpellRankFlat{Value: 20, Coef: 1}},
	},
	ImprovedConcentrationAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 20254, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
		{Rank: 2, SpellID: 20255, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 3, SpellID: 20256, Direct: shared.SpellRankFlat{Value: 15, Coef: 1}},
	},
	ImprovedDevotionAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 20138, Direct: shared.SpellRankFlat{Value: 8, Coef: 1}},
		{Rank: 2, SpellID: 20139, Direct: shared.SpellRankFlat{Value: 16, Coef: 1}},
		{Rank: 3, SpellID: 20140, Direct: shared.SpellRankFlat{Value: 24, Coef: 1}},
		{Rank: 4, SpellID: 20141, Direct: shared.SpellRankFlat{Value: 32, Coef: 1}},
		{Rank: 5, SpellID: 20142, Direct: shared.SpellRankFlat{Value: 40, Coef: 1}},
	},
	ImprovedHammerOfJustice: shared.SpellRankTable{
		{Rank: 1, SpellID: 20487},
		{Rank: 2, SpellID: 20488},
		{Rank: 3, SpellID: 20489},
	},
	ImprovedHolyShield: shared.SpellRankTable{
		{Rank: 1, SpellID: 41021, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 41026, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
	},
	ImprovedJudgement: shared.SpellRankTable{
		{Rank: 1, SpellID: 25956},
		{Rank: 2, SpellID: 25957},
	},
	ImprovedRetributionAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 20091, Direct: shared.SpellRankFlat{Value: 25, Coef: 1}},
		{Rank: 2, SpellID: 20092, Direct: shared.SpellRankFlat{Value: 50, Coef: 1}},
	},
	ImprovedRighteousFury: shared.SpellRankTable{
		{Rank: 1, SpellID: 20468, Direct: shared.SpellRankFlat{Value: 16, Coef: 1}},
		{Rank: 2, SpellID: 20469, Direct: shared.SpellRankFlat{Value: 33, Coef: 1}},
		{Rank: 3, SpellID: 20470, Direct: shared.SpellRankFlat{Value: 50, Coef: 1}},
	},
	ImprovedSanctityAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 31869},
		{Rank: 2, SpellID: 31870, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
	},
	ImprovedSealOfTheCrusader: shared.SpellRankTable{
		{Rank: 1, SpellID: 20335},
		{Rank: 2, SpellID: 20336, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 20337, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
	},
	JudgementOfBlood: shared.SpellRankTable{
		{Rank: 1, SpellID: 31898, MaxRange: 50000, Direct: shared.SpellRankRange{Min: 331, Max: 362, Coef: 0.42899999022483826}},
	},
	JudgementOfCorruption: shared.SpellRankTable{
		{Rank: 1, SpellID: 356112, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 120, Coef: 0.42899999022483826}},
	},
	JudgementOfJustice: shared.SpellRankTable{
		{Rank: 1, SpellID: 20184, MaxRange: 100},
		{Rank: 2, SpellID: 31896, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 7, Coef: 0}},
	},
	JudgementOfLight: shared.SpellRankTable{
		{Rank: 1, SpellID: 20185, MaxRange: 100},
		{Rank: 2, SpellID: 20344, MaxRange: 100},
		{Rank: 3, SpellID: 20345, MaxRange: 100},
		{Rank: 4, SpellID: 20346, MaxRange: 100},
		{Rank: 5, SpellID: 27162, MaxRange: 100},
	},
	JudgementOfRighteousness: shared.SpellRankTable{
		{Rank: 1, SpellID: 20187, MaxRange: 100, Direct: shared.SpellRankRange{Min: 25, Max: 26, Coef: 0.20900000631809235}},
		{Rank: 2, SpellID: 20280, MaxRange: 100, Direct: shared.SpellRankRange{Min: 36, Max: 39, Coef: 0.45500001311302185}},
		{Rank: 3, SpellID: 20281, MaxRange: 100, Direct: shared.SpellRankRange{Min: 53, Max: 58, Coef: 0.6740000247955322}},
		{Rank: 4, SpellID: 20282, MaxRange: 100, Direct: shared.SpellRankRange{Min: 73, Max: 80, Coef: 0.7279999852180481}},
		{Rank: 5, SpellID: 20283, MaxRange: 100, Direct: shared.SpellRankRange{Min: 96, Max: 105, Coef: 0.7279999852180481}},
		{Rank: 6, SpellID: 20284, MaxRange: 100, Direct: shared.SpellRankRange{Min: 124, Max: 135, Coef: 0.7279999852180481}},
		{Rank: 7, SpellID: 20285, MaxRange: 100, Direct: shared.SpellRankRange{Min: 155, Max: 168, Coef: 0.7279999852180481}},
		{Rank: 8, SpellID: 20286, MaxRange: 100, Direct: shared.SpellRankRange{Min: 186, Max: 203, Coef: 0.7279999852180481}},
		{Rank: 9, SpellID: 27157, MaxRange: 100, Direct: shared.SpellRankRange{Min: 225, Max: 246, Coef: 0.7279999852180481}},
	},
	JudgementOfVengeance: shared.SpellRankTable{
		{Rank: 1, SpellID: 31804, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 120, Coef: 0.42899999022483826}},
	},
	JudgementOfWisdom: shared.SpellRankTable{
		{Rank: 1, SpellID: 20186, MaxRange: 100},
		{Rank: 2, SpellID: 20354, MaxRange: 100},
		{Rank: 3, SpellID: 20355, MaxRange: 100},
		{Rank: 4, SpellID: 27164, MaxRange: 100},
	},
	JudgementOfTheCrusader: shared.SpellRankTable{
		{Rank: 1, SpellID: 21183, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 23, Coef: 0}},
		{Rank: 2, SpellID: 20188, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
		{Rank: 3, SpellID: 20300, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 58, Coef: 0}},
		{Rank: 4, SpellID: 20301, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 92, Coef: 0}},
		{Rank: 5, SpellID: 20302, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 127, Coef: 0}},
		{Rank: 6, SpellID: 20303, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 161, Coef: 0}},
		{Rank: 7, SpellID: 27159, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 219, Coef: 0}},
	},
	LayOnHands: shared.SpellRankTable{
		{Rank: 1, SpellID: 633, GCD: 1500 * time.Millisecond, Cooldown: 3600000 * time.Millisecond, MaxRange: 40},
		{Rank: 2, SpellID: 2800, GCD: 1500 * time.Millisecond, Cooldown: 3600000 * time.Millisecond, MaxRange: 40, Energize: shared.SpellRankFlat{Value: 250, Coef: 0}},
		{Rank: 3, SpellID: 10310, GCD: 1500 * time.Millisecond, Cooldown: 3600000 * time.Millisecond, MaxRange: 40, Energize: shared.SpellRankFlat{Value: 550, Coef: 0}},
		{Rank: 4, SpellID: 27154, GCD: 1500 * time.Millisecond, Cooldown: 3600000 * time.Millisecond, MaxRange: 40, Energize: shared.SpellRankFlat{Value: 900, Coef: 0}},
	},
	LightsGrace: shared.SpellRankTable{
		{Rank: 1, SpellID: 31833},
		{Rank: 2, SpellID: 31835},
		{Rank: 3, SpellID: 31836},
	},
	OneHandedWeaponSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 20196},
		{Rank: 2, SpellID: 20197, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 20198, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 20199, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 20200, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	Precision: shared.SpellRankTable{
		{Rank: 1, SpellID: 20189},
		{Rank: 2, SpellID: 20192, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 20193, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
	},
	PureOfHeart: shared.SpellRankTable{
		{Rank: 1, SpellID: 31822, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 31823, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 31824, Direct: shared.SpellRankFlat{Value: 16, Coef: 0}},
	},
	PurifyingPower: shared.SpellRankTable{
		{Rank: 1, SpellID: 31825, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 31826, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
	},
	PursuitOfJustice: shared.SpellRankTable{
		{Rank: 1, SpellID: 26022, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
		{Rank: 2, SpellID: 26023, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 3, SpellID: 44414, Direct: shared.SpellRankFlat{Value: 15, Coef: 1}},
	},
	Reckoning: shared.SpellRankTable{
		{Rank: 1, SpellID: 20177},
		{Rank: 2, SpellID: 20179},
		{Rank: 3, SpellID: 20181},
		{Rank: 4, SpellID: 20180},
		{Rank: 5, SpellID: 20182},
	},
	Redemption: shared.SpellRankTable{
		{Rank: 1, SpellID: 7328, CastTime: 10000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 2, SpellID: 10322, CastTime: 10000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 3, SpellID: 10324, CastTime: 10000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 4, SpellID: 20772, CastTime: 10000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 5, SpellID: 20773, CastTime: 10000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
	},
	Redoubt: shared.SpellRankTable{
		{Rank: 1, SpellID: 20127},
		{Rank: 2, SpellID: 20130},
		{Rank: 3, SpellID: 20135},
		{Rank: 4, SpellID: 20136},
		{Rank: 5, SpellID: 20137},
	},
	RetributionAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 7294, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 10298, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 3, SpellID: 10299, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 12, Coef: 0}},
		{Rank: 4, SpellID: 10300, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 16, Coef: 0}},
		{Rank: 5, SpellID: 10301, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 6, SpellID: 27150, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 26, Coef: 0}},
	},
	SacredDuty: shared.SpellRankTable{
		{Rank: 1, SpellID: 31848, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 2, SpellID: 31849, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
	},
	SanctifiedJudgement: shared.SpellRankTable{
		{Rank: 1, SpellID: 31876, Direct: shared.SpellRankFlat{Value: 33, Coef: 1}},
		{Rank: 2, SpellID: 31877, Direct: shared.SpellRankFlat{Value: 66, Coef: 1}},
		{Rank: 3, SpellID: 31878, Direct: shared.SpellRankFlat{Value: 100, Coef: 1}},
	},
	SanctifiedLight: shared.SpellRankTable{
		{Rank: 1, SpellID: 20359, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 2, SpellID: 20360, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 3, SpellID: 20361, Direct: shared.SpellRankFlat{Value: 6, Coef: 1}},
	},
	SanctifiedSeals: shared.SpellRankTable{
		{Rank: 1, SpellID: 32043, Direct: shared.SpellRankFlat{Value: 33, Coef: 0}},
		{Rank: 2, SpellID: 35396, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 35397, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
	},
	SealOfBlood: shared.SpellRankTable{
		{Rank: 1, SpellID: 31892, Cost: 210, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
	},
	SealOfCommand: shared.SpellRankTable{
		{Rank: 1, SpellID: 20375, Cost: 65, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20425, Coef: 0}},
		{Rank: 2, SpellID: 20915, Cost: 110, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20962, Coef: 0}},
		{Rank: 3, SpellID: 20918, Cost: 140, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20961, Coef: 0}},
		{Rank: 4, SpellID: 20919, Cost: 180, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20967, Coef: 0}},
		{Rank: 5, SpellID: 20920, Cost: 210, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20968, Coef: 0}},
		{Rank: 6, SpellID: 27170, Cost: 280, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 27172, Coef: 0}},
	},
	SealOfCorruption: shared.SpellRankTable{
		{Rank: 1, SpellID: 348704, Cost: 250, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 356113, Coef: 0}},
	},
	SealOfJustice: shared.SpellRankTable{
		{Rank: 1, SpellID: 20164, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20184, Coef: 0}},
		{Rank: 2, SpellID: 31895, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 31896, Coef: 0}},
	},
	SealOfLight: shared.SpellRankTable{
		{Rank: 1, SpellID: 20165, Cost: 110, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20185, Coef: 0}},
		{Rank: 2, SpellID: 20347, Cost: 140, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20344, Coef: 0}},
		{Rank: 3, SpellID: 20348, Cost: 180, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20345, Coef: 0}},
		{Rank: 4, SpellID: 20349, Cost: 210, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20346, Coef: 0}},
		{Rank: 5, SpellID: 27160, Cost: 280, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 27162, Coef: 0}},
	},
	SealOfVengeance: shared.SpellRankTable{
		{Rank: 1, SpellID: 31801, Cost: 250, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 31804, Coef: 0}},
	},
	SealOfWisdom: shared.SpellRankTable{
		{Rank: 1, SpellID: 20166, Cost: 135, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20186, Coef: 0}},
		{Rank: 2, SpellID: 20356, Cost: 170, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20354, Coef: 0}},
		{Rank: 3, SpellID: 20357, Cost: 200, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20355, Coef: 0}},
		{Rank: 4, SpellID: 27166, Cost: 270, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 27164, Coef: 0}},
	},
	SealOfTheCrusader: shared.SpellRankTable{
		{Rank: 1, SpellID: 21082, Cost: 25, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 40, Max: 41, Coef: 0}},
		{Rank: 2, SpellID: 20162, Cost: 40, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 67, Max: 68, Coef: 0}},
		{Rank: 3, SpellID: 20305, Cost: 65, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 121, Max: 122, Coef: 0}},
		{Rank: 4, SpellID: 20306, Cost: 90, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 183, Coef: 0}},
		{Rank: 5, SpellID: 20307, Cost: 125, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 271, Max: 272, Coef: 0}},
		{Rank: 6, SpellID: 20308, Cost: 160, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 371, Max: 372, Coef: 0}},
		{Rank: 7, SpellID: 27158, Cost: 210, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 494, Max: 495, Coef: 0}},
	},
	SealOfTheMartyr: shared.SpellRankTable{
		{Rank: 1, SpellID: 348700, Cost: 210, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
	},
	ShadowResistanceAura: shared.SpellRankTable{
		{Rank: 1, SpellID: 19876, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 19895, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 45, Coef: 0}},
		{Rank: 3, SpellID: 19896, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 60, Coef: 0}},
		{Rank: 4, SpellID: 27151, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 70, Coef: 0}},
	},
	ShieldSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 20148, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 20149, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 3, SpellID: 20150, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
	},
	SpellWarding: shared.SpellRankTable{
		{Rank: 1, SpellID: 31846},
		{Rank: 2, SpellID: 31847},
	},
	SpiritualAttunement: shared.SpellRankTable{
		{Rank: 1, SpellID: 31785, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 2, SpellID: 33776, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
	},
	Stoicism: shared.SpellRankTable{
		{Rank: 1, SpellID: 31844, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 31845, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
	},
	Toughness: shared.SpellRankTable{
		{Rank: 1, SpellID: 20143, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 20144, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 20145, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 4, SpellID: 20146, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 5, SpellID: 20147, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
	},
	TurnEvil: shared.SpellRankTable{
		{Rank: 1, SpellID: 10326, Cost: 75, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
	},
	TurnUndead: shared.SpellRankTable{
		{Rank: 1, SpellID: 2878, Cost: 35, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 2, SpellID: 5627, Cost: 50, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
	},
	TwoHandedWeaponSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 20111, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 20112, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 20113, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
	},
	UnyieldingFaith: shared.SpellRankTable{
		{Rank: 1, SpellID: 9453, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
		{Rank: 2, SpellID: 25836, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
	},
	Vengeance: shared.SpellRankTable{
		{Rank: 1, SpellID: 20049},
		{Rank: 2, SpellID: 20056},
		{Rank: 3, SpellID: 20057},
		{Rank: 4, SpellID: 20058},
		{Rank: 5, SpellID: 20059},
	},
}
