// Code generated by tools/database/gen_db/gen_bulksim_constants.ts.go. DO NOT EDIT.

import { ItemSlot } from '../../../proto/common';

export enum BulkSimItemSlot {
	ItemSlotHead,
	ItemSlotNeck,
	ItemSlotShoulder,
	ItemSlotBack,
	ItemSlotChest,
	ItemSlotWrist,
	ItemSlotHands,
	ItemSlotWaist,
	ItemSlotLegs,
	ItemSlotFeet,
	ItemSlotFinger,
	ItemSlotTrinket,
	ItemSlotMainHand,
	ItemSlotOffHand,
	ItemSlotRanged,
	ItemSlotHandWeapon,
}

export const ITEM_SLOT_TO_BULK_SIM_ITEM_SLOT: Map<ItemSlot, BulkSimItemSlot> = new Map([
	[ItemSlot.ItemSlotHead, BulkSimItemSlot.ItemSlotHead],
	[ItemSlot.ItemSlotNeck, BulkSimItemSlot.ItemSlotNeck],
	[ItemSlot.ItemSlotShoulder, BulkSimItemSlot.ItemSlotShoulder],
	[ItemSlot.ItemSlotBack, BulkSimItemSlot.ItemSlotBack],
	[ItemSlot.ItemSlotChest, BulkSimItemSlot.ItemSlotChest],
	[ItemSlot.ItemSlotWrist, BulkSimItemSlot.ItemSlotWrist],
	[ItemSlot.ItemSlotHands, BulkSimItemSlot.ItemSlotHands],
	[ItemSlot.ItemSlotWaist, BulkSimItemSlot.ItemSlotWaist],
	[ItemSlot.ItemSlotLegs, BulkSimItemSlot.ItemSlotLegs],
	[ItemSlot.ItemSlotFeet, BulkSimItemSlot.ItemSlotFeet],
	[ItemSlot.ItemSlotFinger1, BulkSimItemSlot.ItemSlotFinger],
	[ItemSlot.ItemSlotFinger2, BulkSimItemSlot.ItemSlotFinger],
	[ItemSlot.ItemSlotTrinket1, BulkSimItemSlot.ItemSlotTrinket],
	[ItemSlot.ItemSlotTrinket2, BulkSimItemSlot.ItemSlotTrinket],
	[ItemSlot.ItemSlotMainHand, BulkSimItemSlot.ItemSlotMainHand],
	[ItemSlot.ItemSlotOffHand, BulkSimItemSlot.ItemSlotOffHand],
	[ItemSlot.ItemSlotRanged, BulkSimItemSlot.ItemSlotRanged],
]);

export const BULK_SIM_ITEM_SLOT_TO_SINGLE_ITEM_SLOT: Map<BulkSimItemSlot, ItemSlot> = new Map([
	[BulkSimItemSlot.ItemSlotHead, ItemSlot.ItemSlotHead],
	[BulkSimItemSlot.ItemSlotNeck, ItemSlot.ItemSlotNeck],
	[BulkSimItemSlot.ItemSlotShoulder, ItemSlot.ItemSlotShoulder],
	[BulkSimItemSlot.ItemSlotBack, ItemSlot.ItemSlotBack],
	[BulkSimItemSlot.ItemSlotChest, ItemSlot.ItemSlotChest],
	[BulkSimItemSlot.ItemSlotWrist, ItemSlot.ItemSlotWrist],
	[BulkSimItemSlot.ItemSlotHands, ItemSlot.ItemSlotHands],
	[BulkSimItemSlot.ItemSlotWaist, ItemSlot.ItemSlotWaist],
	[BulkSimItemSlot.ItemSlotLegs, ItemSlot.ItemSlotLegs],
	[BulkSimItemSlot.ItemSlotFeet, ItemSlot.ItemSlotFeet],
	[BulkSimItemSlot.ItemSlotMainHand, ItemSlot.ItemSlotMainHand],
	[BulkSimItemSlot.ItemSlotOffHand, ItemSlot.ItemSlotOffHand],
	[BulkSimItemSlot.ItemSlotRanged, ItemSlot.ItemSlotRanged],
]);

export const BULK_SIM_ITEM_SLOT_TO_ITEM_SLOT_PAIRS: Map<BulkSimItemSlot, [ItemSlot, ItemSlot]> = new Map([
	[BulkSimItemSlot.ItemSlotFinger, [ItemSlot.ItemSlotFinger1, ItemSlot.ItemSlotFinger2]],
	[BulkSimItemSlot.ItemSlotTrinket, [ItemSlot.ItemSlotTrinket1, ItemSlot.ItemSlotTrinket2]],
	[BulkSimItemSlot.ItemSlotHandWeapon, [ItemSlot.ItemSlotMainHand, ItemSlot.ItemSlotOffHand]],
]);
