package database

import (
	"bytes"
	"fmt"
	"maps"
	"os"
	"slices"
	"text/template"

	"github.com/wowsims/tbc/sim/core/bulk"
	"github.com/wowsims/tbc/sim/core/proto"
)

const bulkSimConstantsTSOutputPath = "ui/core/components/individual_sim_ui/bulk/constants_auto_gen.ts"

type tsBulkItemSlotToBulkSlot struct {
	ItemSlotName string
	BulkSlotName string
}

type tsBulkBulkSlotToItemSlot struct {
	BulkSlotName string
	ItemSlotName string
}

type tsBulkBulkSlotToItemSlotPair struct {
	BulkSlotName string
	FirstSlot    string
	SecondSlot   string
}

type tsBulkConstants struct {
	BulkSlotNames            []string
	ItemSlotToBulkSlot       []tsBulkItemSlotToBulkSlot
	BulkSlotToSingleItemSlot []tsBulkBulkSlotToItemSlot
	BulkSlotToItemSlotPairs  []tsBulkBulkSlotToItemSlotPair
}

const bulkConstantsTSTemplate = `// Code generated by tools/database/gen_db/gen_bulksim_constants.ts.go. DO NOT EDIT.

import { ItemSlot } from '../../../proto/common';

export enum BulkSimItemSlot {
{{- range .BulkSlotNames }}
	{{ . }},
{{- end }}
}

export const ITEM_SLOT_TO_BULK_SIM_ITEM_SLOT: Map<ItemSlot, BulkSimItemSlot> = new Map([
{{- range .ItemSlotToBulkSlot }}
	[ItemSlot.{{ .ItemSlotName }}, BulkSimItemSlot.{{ .BulkSlotName }}],
{{- end }}
]);

export const BULK_SIM_ITEM_SLOT_TO_SINGLE_ITEM_SLOT: Map<BulkSimItemSlot, ItemSlot> = new Map([
{{- range .BulkSlotToSingleItemSlot }}
	[BulkSimItemSlot.{{ .BulkSlotName }}, ItemSlot.{{ .ItemSlotName }}],
{{- end }}
]);

export const BULK_SIM_ITEM_SLOT_TO_ITEM_SLOT_PAIRS: Map<BulkSimItemSlot, [ItemSlot, ItemSlot]> = new Map([
{{- range .BulkSlotToItemSlotPairs }}
	[BulkSimItemSlot.{{ .BulkSlotName }}, [ItemSlot.{{ .FirstSlot }}, ItemSlot.{{ .SecondSlot }}]],
{{- end }}
]);
`

func GenerateBulkSimConstantsTSFile() error {
	bulkSlotIDs := make([]bulk.BulkSimItemSlot, 0, len(bulk.BulkSimItemSlotNames))
	for bulkSlotID := range bulk.BulkSimItemSlotNames {
		bulkSlotIDs = append(bulkSlotIDs, bulkSlotID)
	}
	slices.Sort(bulkSlotIDs)

	bulkSlotNames := make([]string, 0, len(bulkSlotIDs))
	for _, bulkSlotID := range bulkSlotIDs {
		bulkSlotNames = append(bulkSlotNames, bulk.BulkSimItemSlotNames[bulkSlotID])
	}

	itemSlotIDs := slices.Sorted(maps.Keys(bulk.ItemSlotToBulkSimItemSlot))
	itemSlotToBulkSlot := make([]tsBulkItemSlotToBulkSlot, 0, len(itemSlotIDs))
	for _, itemSlotID := range itemSlotIDs {
		itemSlotToBulkSlot = append(itemSlotToBulkSlot, tsBulkItemSlotToBulkSlot{
			ItemSlotName: proto.ItemSlot_name[int32(itemSlotID)],
			BulkSlotName: bulk.BulkSimItemSlotNames[bulk.ItemSlotToBulkSimItemSlot[itemSlotID]],
		})
	}

	bulkSlotToSingleItemSlot := make([]tsBulkBulkSlotToItemSlot, 0, len(bulk.BulkSimItemSlotToSingleItemSlot))
	for _, bulkSlotID := range bulkSlotIDs {
		itemSlotID, ok := bulk.BulkSimItemSlotToSingleItemSlot[bulkSlotID]
		if !ok {
			continue
		}
		bulkSlotToSingleItemSlot = append(bulkSlotToSingleItemSlot, tsBulkBulkSlotToItemSlot{
			BulkSlotName: bulk.BulkSimItemSlotNames[bulkSlotID],
			ItemSlotName: proto.ItemSlot_name[int32(itemSlotID)],
		})
	}

	bulkSlotToItemSlotPairs := make([]tsBulkBulkSlotToItemSlotPair, 0, len(bulk.BulkSimItemSlotToItemSlotPairs))
	for _, bulkSlotID := range bulkSlotIDs {
		itemSlots, ok := bulk.BulkSimItemSlotToItemSlotPairs[bulkSlotID]
		if !ok {
			continue
		}
		bulkSlotToItemSlotPairs = append(bulkSlotToItemSlotPairs, tsBulkBulkSlotToItemSlotPair{
			BulkSlotName: bulk.BulkSimItemSlotNames[bulkSlotID],
			FirstSlot:    proto.ItemSlot_name[int32(itemSlots[0])],
			SecondSlot:   proto.ItemSlot_name[int32(itemSlots[1])],
		})
	}

	tpl, err := template.New("bulkConstantsTS").Parse(bulkConstantsTSTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse bulk constants TS template: %w", err)
	}

	var buf bytes.Buffer
	if err := tpl.Execute(&buf, tsBulkConstants{
		BulkSlotNames:            bulkSlotNames,
		ItemSlotToBulkSlot:       itemSlotToBulkSlot,
		BulkSlotToSingleItemSlot: bulkSlotToSingleItemSlot,
		BulkSlotToItemSlotPairs:  bulkSlotToItemSlotPairs,
	}); err != nil {
		return fmt.Errorf("failed to execute bulk constants TS template: %w", err)
	}

	if err := os.WriteFile(bulkSimConstantsTSOutputPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write generated bulk constants TS file: %w", err)
	}

	return nil
}
