// Code generated by tools/database/gen_db -gen=spellranks. DO NOT EDIT.

package warrior

import (
	"time"

	"github.com/wowsims/tbc/sim/common/shared"
)

// Not generated:
//   Flurry: rank 1 is ambiguous between spells 12319, 12966
//   Rampage: rank 1 is ambiguous between spells 29801, 30029
//   Second Wind: rank 1 is ambiguous between spells 29834, 29841
//   Sweeping Strikes: rank 1 is ambiguous between spells 12723, 26654
//   Unbridled Wrath: rank 1 is ambiguous between spells 12322, 12964

type generatedRanks struct {
	Anticipation                  shared.SpellRankTable
	BattleShout                   shared.SpellRankTable
	BloodCraze                    shared.SpellRankTable
	BloodFrenzy                   shared.SpellRankTable
	Bloodthirst                   shared.SpellRankTable
	BoomingVoice                  shared.SpellRankTable
	Charge                        shared.SpellRankTable
	ChargeRageBonusEffect         shared.SpellRankTable
	Cleave                        shared.SpellRankTable
	CommandingPresence            shared.SpellRankTable
	CommandingShout               shared.SpellRankTable
	Cruelty                       shared.SpellRankTable
	DeepWounds                    shared.SpellRankTable
	Defiance                      shared.SpellRankTable
	Deflection                    shared.SpellRankTable
	DemoralizingShout             shared.SpellRankTable
	Devastate                     shared.SpellRankTable
	DualWieldSpecialization       shared.SpellRankTable
	Enrage                        shared.SpellRankTable
	Execute                       shared.SpellRankTable
	FocusedRage                   shared.SpellRankTable
	Hamstring                     shared.SpellRankTable
	HeroicStrike                  shared.SpellRankTable
	Impale                        shared.SpellRankTable
	ImprovedBerserkerRage         shared.SpellRankTable
	ImprovedBerserkerStance       shared.SpellRankTable
	ImprovedBloodrage             shared.SpellRankTable
	ImprovedChallengingShout      shared.SpellRankTable
	ImprovedCharge                shared.SpellRankTable
	ImprovedCleave                shared.SpellRankTable
	ImprovedDefensiveStance       shared.SpellRankTable
	ImprovedDemoralizingShout     shared.SpellRankTable
	ImprovedDisarm                shared.SpellRankTable
	ImprovedDisciplines           shared.SpellRankTable
	ImprovedExecute               shared.SpellRankTable
	ImprovedHamstring             shared.SpellRankTable
	ImprovedHeroicStrike          shared.SpellRankTable
	ImprovedIntercept             shared.SpellRankTable
	ImprovedIntimidatingShout     shared.SpellRankTable
	ImprovedMortalStrike          shared.SpellRankTable
	ImprovedOverpower             shared.SpellRankTable
	ImprovedRend                  shared.SpellRankTable
	ImprovedRevenge               shared.SpellRankTable
	ImprovedShieldBash            shared.SpellRankTable
	ImprovedShieldBlock           shared.SpellRankTable
	ImprovedShieldWall            shared.SpellRankTable
	ImprovedSlam                  shared.SpellRankTable
	ImprovedSunderArmor           shared.SpellRankTable
	ImprovedTaunt                 shared.SpellRankTable
	ImprovedThunderClap           shared.SpellRankTable
	ImprovedWhirlwind             shared.SpellRankTable
	Intercept                     shared.SpellRankTable
	IronWill                      shared.SpellRankTable
	LongDaze                      shared.SpellRankTable
	MaceSpecialization            shared.SpellRankTable
	MaceStunEffect                shared.SpellRankTable
	MockingBlow                   shared.SpellRankTable
	MortalStrike                  shared.SpellRankTable
	OneHandedWeaponSpecialization shared.SpellRankTable
	Overpower                     shared.SpellRankTable
	PoleaxeSpecialization         shared.SpellRankTable
	Precision                     shared.SpellRankTable
	Pummel                        shared.SpellRankTable
	Rend                          shared.SpellRankTable
	Revenge                       shared.SpellRankTable
	RevengeStun                   shared.SpellRankTable
	ShieldBash                    shared.SpellRankTable
	ShieldMastery                 shared.SpellRankTable
	ShieldSlam                    shared.SpellRankTable
	ShieldSpecialization          shared.SpellRankTable
	Slam                          shared.SpellRankTable
	SunderArmor                   shared.SpellRankTable
	SwordSpecialization           shared.SpellRankTable
	TacticalMastery               shared.SpellRankTable
	ThunderClap                   shared.SpellRankTable
	Toughness                     shared.SpellRankTable
	TwoHandedWeaponSpecialization shared.SpellRankTable
	VictoryRush                   shared.SpellRankTable
	Vitality                      shared.SpellRankTable
	WeaponMastery                 shared.SpellRankTable
}

var genRanks = generatedRanks{
	Anticipation: shared.SpellRankTable{
		{Rank: 1, SpellID: 12297, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 2, SpellID: 12750, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 3, SpellID: 12751, Direct: shared.SpellRankFlat{Value: 12, Coef: 0}},
		{Rank: 4, SpellID: 12752, Direct: shared.SpellRankFlat{Value: 16, Coef: 0}},
		{Rank: 5, SpellID: 12753, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
	},
	BattleShout: shared.SpellRankTable{
		{Rank: 1, SpellID: 6673, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 2, SpellID: 5242, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 39, Max: 40, Coef: 0}},
		{Rank: 3, SpellID: 6192, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 59, Max: 60, Coef: 0}},
		{Rank: 4, SpellID: 11549, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 94, Coef: 0}},
		{Rank: 5, SpellID: 11550, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 139, Coef: 0}},
		{Rank: 6, SpellID: 11551, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 194, Coef: 0}},
		{Rank: 7, SpellID: 25289, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 240, Coef: 0}},
		{Rank: 8, SpellID: 2048, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 306, Coef: 1}},
	},
	BloodCraze: shared.SpellRankTable{
		{Rank: 1, SpellID: 16487},
		{Rank: 2, SpellID: 16489},
		{Rank: 3, SpellID: 16492},
	},
	BloodFrenzy: shared.SpellRankTable{
		{Rank: 1, SpellID: 29836, Direct: shared.SpellRankFlat{Value: 100, Coef: 0}},
		{Rank: 2, SpellID: 29859, Direct: shared.SpellRankFlat{Value: 100, Coef: 0}},
	},
	Bloodthirst: shared.SpellRankTable{
		{Rank: 1, SpellID: 23881, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
		{Rank: 2, SpellID: 23892, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
		{Rank: 3, SpellID: 23893, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
		{Rank: 4, SpellID: 23894, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
		{Rank: 5, SpellID: 25251, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
		{Rank: 6, SpellID: 30335, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
	},
	BoomingVoice: shared.SpellRankTable{
		{Rank: 1, SpellID: 12321, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 12835, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 3, SpellID: 12836, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 4, SpellID: 12837, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
		{Rank: 5, SpellID: 12838, Direct: shared.SpellRankFlat{Value: 50, Coef: 0}},
	},
	Charge: shared.SpellRankTable{
		{Rank: 1, SpellID: 100, Cooldown: 15000 * time.Millisecond, MaxRange: 25},
		{Rank: 2, SpellID: 6178, Cooldown: 15000 * time.Millisecond, MaxRange: 25},
		{Rank: 3, SpellID: 11578, Cooldown: 15000 * time.Millisecond, MaxRange: 25},
	},
	ChargeRageBonusEffect: shared.SpellRankTable{
		{Rank: 1, SpellID: 12695, Energize: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 12696, Energize: shared.SpellRankFlat{Value: 60, Coef: 0}},
	},
	Cleave: shared.SpellRankTable{
		{Rank: 1, SpellID: 845, Cost: 20, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
		{Rank: 2, SpellID: 7369, Cost: 20, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 3, SpellID: 11608, Cost: 20, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 18, Coef: 1}},
		{Rank: 4, SpellID: 11609, Cost: 20, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 32, Coef: 1}},
		{Rank: 5, SpellID: 20569, Cost: 20, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 50, Coef: 1}},
		{Rank: 6, SpellID: 25231, Cost: 20, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 70, Coef: 1}},
	},
	CommandingPresence: shared.SpellRankTable{
		{Rank: 1, SpellID: 12318, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 12857, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 12858, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 4, SpellID: 12860, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 5, SpellID: 12861, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
	},
	CommandingShout: shared.SpellRankTable{
		{Rank: 1, SpellID: 469, Cost: 10, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 1080, Coef: 1}},
	},
	Cruelty: shared.SpellRankTable{
		{Rank: 1, SpellID: 12320},
		{Rank: 2, SpellID: 12852, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 12853, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 12855, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 12856, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	DeepWounds: shared.SpellRankTable{
		{Rank: 1, SpellID: 12834},
		{Rank: 2, SpellID: 12849},
		{Rank: 3, SpellID: 12867},
	},
	Defiance: shared.SpellRankTable{
		{Rank: 1, SpellID: 12303, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 12788, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 12789, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
	},
	Deflection: shared.SpellRankTable{
		{Rank: 1, SpellID: 16462},
		{Rank: 2, SpellID: 16463, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 16464, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
		{Rank: 4, SpellID: 16465, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 5, SpellID: 16466, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
	},
	DemoralizingShout: shared.SpellRankTable{
		{Rank: 1, SpellID: 1160, Cost: 10, GCD: 1500 * time.Millisecond},
		{Rank: 2, SpellID: 6190, Cost: 10, GCD: 1500 * time.Millisecond},
		{Rank: 3, SpellID: 11554, Cost: 10, GCD: 1500 * time.Millisecond},
		{Rank: 4, SpellID: 11555, Cost: 10, GCD: 1500 * time.Millisecond},
		{Rank: 5, SpellID: 11556, Cost: 10, GCD: 1500 * time.Millisecond},
		{Rank: 6, SpellID: 25202, Cost: 10, GCD: 1500 * time.Millisecond},
		{Rank: 7, SpellID: 25203, Cost: 10, GCD: 1500 * time.Millisecond},
	},
	Devastate: shared.SpellRankTable{
		{Rank: 1, SpellID: 20243, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 2, SpellID: 30016, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 3, SpellID: 30022, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
	},
	DualWieldSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 23584, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
		{Rank: 2, SpellID: 23585, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 3, SpellID: 23586, Direct: shared.SpellRankFlat{Value: 15, Coef: 1}},
		{Rank: 4, SpellID: 23587, Direct: shared.SpellRankFlat{Value: 20, Coef: 1}},
		{Rank: 5, SpellID: 23588, Direct: shared.SpellRankFlat{Value: 25, Coef: 1}},
	},
	Enrage: shared.SpellRankTable{
		{Rank: 1, SpellID: 12317},
		{Rank: 2, SpellID: 13045},
		{Rank: 3, SpellID: 13046},
		{Rank: 4, SpellID: 13047},
		{Rank: 5, SpellID: 13048},
	},
	Execute: shared.SpellRankTable{
		{Rank: 1, SpellID: 5308, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 2, SpellID: 20658, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 3, SpellID: 20660, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 4, SpellID: 20661, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 5, SpellID: 20662, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 6, SpellID: 25234, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 7, SpellID: 25236, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
	},
	FocusedRage: shared.SpellRankTable{
		{Rank: 1, SpellID: 29787},
		{Rank: 2, SpellID: 29790},
		{Rank: 3, SpellID: 29792},
	},
	Hamstring: shared.SpellRankTable{
		{Rank: 1, SpellID: 1715, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
		{Rank: 2, SpellID: 7372, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 18, Coef: 1}},
		{Rank: 3, SpellID: 7373, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
		{Rank: 4, SpellID: 25212, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 63, Coef: 1}},
	},
	HeroicStrike: shared.SpellRankTable{
		{Rank: 1, SpellID: 78, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 11, Coef: 1}},
		{Rank: 2, SpellID: 284, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 21, Coef: 1}},
		{Rank: 3, SpellID: 285, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 32, Coef: 1}},
		{Rank: 4, SpellID: 1608, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 44, Coef: 1}},
		{Rank: 5, SpellID: 11564, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 58, Coef: 1}},
		{Rank: 6, SpellID: 11565, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 80, Coef: 1}},
		{Rank: 7, SpellID: 11566, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 111, Coef: 1}},
		{Rank: 8, SpellID: 11567, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 138, Coef: 1}},
		{Rank: 9, SpellID: 25286, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 157, Coef: 1}},
		{Rank: 10, SpellID: 29707, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 176, Coef: 1}},
		{Rank: 11, SpellID: 30324, Cost: 15, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 208, Coef: 1}},
	},
	Impale: shared.SpellRankTable{
		{Rank: 1, SpellID: 16493, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 2, SpellID: 16494, Direct: shared.SpellRankFlat{Value: 20, Coef: 1}},
	},
	ImprovedBerserkerRage: shared.SpellRankTable{
		{Rank: 1, SpellID: 20500},
		{Rank: 2, SpellID: 20501},
	},
	ImprovedBerserkerStance: shared.SpellRankTable{
		{Rank: 1, SpellID: 29759, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 2, SpellID: 29760, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 3, SpellID: 29761, Direct: shared.SpellRankFlat{Value: 6, Coef: 1}},
		{Rank: 4, SpellID: 29762, Direct: shared.SpellRankFlat{Value: 8, Coef: 1}},
		{Rank: 5, SpellID: 29763, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
	},
	ImprovedBloodrage: shared.SpellRankTable{
		{Rank: 1, SpellID: 12301, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 12818, Direct: shared.SpellRankFlat{Value: 60, Coef: 0}},
	},
	ImprovedChallengingShout: shared.SpellRankTable{
		{Rank: 1, SpellID: 12327},
		{Rank: 2, SpellID: 12886},
	},
	ImprovedCharge: shared.SpellRankTable{
		{Rank: 1, SpellID: 12285, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 12697, Direct: shared.SpellRankFlat{Value: 60, Coef: 0}},
	},
	ImprovedCleave: shared.SpellRankTable{
		{Rank: 1, SpellID: 12329, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
		{Rank: 2, SpellID: 12950, Direct: shared.SpellRankFlat{Value: 80, Coef: 0}},
		{Rank: 3, SpellID: 20496, Direct: shared.SpellRankFlat{Value: 120, Coef: 0}},
	},
	ImprovedDefensiveStance: shared.SpellRankTable{
		{Rank: 1, SpellID: 29593},
		{Rank: 2, SpellID: 29594},
		{Rank: 3, SpellID: 29595},
	},
	ImprovedDemoralizingShout: shared.SpellRankTable{
		{Rank: 1, SpellID: 12324, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 2, SpellID: 12876, Direct: shared.SpellRankFlat{Value: 16, Coef: 0}},
		{Rank: 3, SpellID: 12877, Direct: shared.SpellRankFlat{Value: 24, Coef: 0}},
		{Rank: 4, SpellID: 12878, Direct: shared.SpellRankFlat{Value: 32, Coef: 0}},
		{Rank: 5, SpellID: 12879, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
	},
	ImprovedDisarm: shared.SpellRankTable{
		{Rank: 1, SpellID: 12313, Direct: shared.SpellRankFlat{Value: 1000, Coef: 0}},
		{Rank: 2, SpellID: 12804, Direct: shared.SpellRankFlat{Value: 2000, Coef: 0}},
		{Rank: 3, SpellID: 12807, Direct: shared.SpellRankFlat{Value: 3000, Coef: 0}},
	},
	ImprovedDisciplines: shared.SpellRankTable{
		{Rank: 1, SpellID: 29723, Direct: shared.SpellRankFlat{Value: 2000, Coef: 0}},
		{Rank: 2, SpellID: 29724, Direct: shared.SpellRankFlat{Value: 4000, Coef: 0}},
		{Rank: 3, SpellID: 29725, Direct: shared.SpellRankFlat{Value: 6000, Coef: 0}},
	},
	ImprovedExecute: shared.SpellRankTable{
		{Rank: 1, SpellID: 20502},
		{Rank: 2, SpellID: 20503},
	},
	ImprovedHamstring: shared.SpellRankTable{
		{Rank: 1, SpellID: 12289},
		{Rank: 2, SpellID: 12668},
		{Rank: 3, SpellID: 23695},
	},
	ImprovedHeroicStrike: shared.SpellRankTable{
		{Rank: 1, SpellID: 12282},
		{Rank: 2, SpellID: 12663},
		{Rank: 3, SpellID: 12664},
	},
	ImprovedIntercept: shared.SpellRankTable{
		{Rank: 1, SpellID: 29888},
		{Rank: 2, SpellID: 29889},
	},
	ImprovedIntimidatingShout: shared.SpellRankTable{
		{Rank: 1, SpellID: 19870, Direct: shared.SpellRankFlat{Value: 1000, Coef: 1}},
		{Rank: 2, SpellID: 19871, Direct: shared.SpellRankFlat{Value: 2000, Coef: 1}},
	},
	ImprovedMortalStrike: shared.SpellRankTable{
		{Rank: 1, SpellID: 35446},
		{Rank: 2, SpellID: 35448, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 35449, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 35450, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 35451, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	ImprovedOverpower: shared.SpellRankTable{
		{Rank: 1, SpellID: 12290, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 2, SpellID: 12963, Direct: shared.SpellRankFlat{Value: 50, Coef: 0}},
	},
	ImprovedRend: shared.SpellRankTable{
		{Rank: 1, SpellID: 12286, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 2, SpellID: 12658, Direct: shared.SpellRankFlat{Value: 50, Coef: 0}},
		{Rank: 3, SpellID: 12659, Direct: shared.SpellRankFlat{Value: 75, Coef: 0}},
	},
	ImprovedRevenge: shared.SpellRankTable{
		{Rank: 1, SpellID: 12797},
		{Rank: 2, SpellID: 12799},
		{Rank: 3, SpellID: 12800},
	},
	ImprovedShieldBash: shared.SpellRankTable{
		{Rank: 1, SpellID: 12311},
		{Rank: 2, SpellID: 12958},
	},
	ImprovedShieldBlock: shared.SpellRankTable{
		{Rank: 1, SpellID: 12945, Direct: shared.SpellRankFlat{Value: 1000, Coef: 0}},
	},
	ImprovedShieldWall: shared.SpellRankTable{
		{Rank: 1, SpellID: 12312, Direct: shared.SpellRankFlat{Value: 3000, Coef: 0}},
		{Rank: 2, SpellID: 12803, Direct: shared.SpellRankFlat{Value: 5000, Coef: 0}},
	},
	ImprovedSlam: shared.SpellRankTable{
		{Rank: 1, SpellID: 12862},
		{Rank: 2, SpellID: 12330},
	},
	ImprovedSunderArmor: shared.SpellRankTable{
		{Rank: 1, SpellID: 12308},
		{Rank: 2, SpellID: 12810},
		{Rank: 3, SpellID: 12811},
	},
	ImprovedTaunt: shared.SpellRankTable{
		{Rank: 1, SpellID: 12302},
		{Rank: 2, SpellID: 12765},
	},
	ImprovedThunderClap: shared.SpellRankTable{
		{Rank: 1, SpellID: 12287, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
		{Rank: 2, SpellID: 12665, Direct: shared.SpellRankFlat{Value: 70, Coef: 0}},
		{Rank: 3, SpellID: 12666, Direct: shared.SpellRankFlat{Value: 100, Coef: 0}},
	},
	ImprovedWhirlwind: shared.SpellRankTable{
		{Rank: 1, SpellID: 29721},
		{Rank: 2, SpellID: 29776},
	},
	Intercept: shared.SpellRankTable{
		{Rank: 1, SpellID: 20252, Cost: 10, Cooldown: 30000 * time.Millisecond, MaxRange: 25},
		{Rank: 2, SpellID: 20616, Cost: 10, Cooldown: 30000 * time.Millisecond, MaxRange: 25},
		{Rank: 3, SpellID: 20617, Cost: 10, Cooldown: 30000 * time.Millisecond, MaxRange: 25},
		{Rank: 4, SpellID: 25272, Cost: 10, Cooldown: 30000 * time.Millisecond, MaxRange: 25},
		{Rank: 5, SpellID: 25275, Cost: 10, Cooldown: 30000 * time.Millisecond, MaxRange: 25},
	},
	IronWill: shared.SpellRankTable{
		{Rank: 1, SpellID: 12300, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 2, SpellID: 12959, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 3, SpellID: 12960, Direct: shared.SpellRankFlat{Value: 9, Coef: 0}},
		{Rank: 4, SpellID: 12961, Direct: shared.SpellRankFlat{Value: 12, Coef: 0}},
		{Rank: 5, SpellID: 12962, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
	},
	LongDaze: shared.SpellRankTable{
		{Rank: 1, SpellID: 12705, MaxRange: 100},
	},
	MaceSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 12284},
		{Rank: 2, SpellID: 12701},
		{Rank: 3, SpellID: 12702},
		{Rank: 4, SpellID: 12703},
		{Rank: 5, SpellID: 12704},
	},
	MaceStunEffect: shared.SpellRankTable{
		{Rank: 1, SpellID: 5530, Energize: shared.SpellRankFlat{Value: 70, Coef: 0}},
	},
	MockingBlow: shared.SpellRankTable{
		{Rank: 1, SpellID: 694, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 120000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 22, Coef: 1}},
		{Rank: 2, SpellID: 7400, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 120000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 31, Coef: 1}},
		{Rank: 3, SpellID: 7402, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 120000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 46, Coef: 1}},
		{Rank: 4, SpellID: 20559, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 120000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 71, Coef: 1}},
		{Rank: 5, SpellID: 20560, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 120000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 93, Coef: 1}},
		{Rank: 6, SpellID: 25266, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 120000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 114, Coef: 1}},
	},
	MortalStrike: shared.SpellRankTable{
		{Rank: 1, SpellID: 12294, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 85, Coef: 1}},
		{Rank: 2, SpellID: 21551, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 110, Coef: 1}},
		{Rank: 3, SpellID: 21552, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 135, Coef: 1}},
		{Rank: 4, SpellID: 21553, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 160, Coef: 1}},
		{Rank: 5, SpellID: 25248, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 185, Coef: 1}},
		{Rank: 6, SpellID: 30330, Cost: 30, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 210, Coef: 1}},
	},
	OneHandedWeaponSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 16538, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 16539, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 16540, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 4, SpellID: 16541, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 5, SpellID: 16542, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
	},
	Overpower: shared.SpellRankTable{
		{Rank: 1, SpellID: 7384, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
		{Rank: 2, SpellID: 7887, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 15, Coef: 1}},
		{Rank: 3, SpellID: 11584, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 25, Coef: 1}},
		{Rank: 4, SpellID: 11585, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 35, Coef: 1}},
	},
	PoleaxeSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 12700},
		{Rank: 2, SpellID: 12781, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 12783, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 12784, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 12785, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	Precision: shared.SpellRankTable{
		{Rank: 1, SpellID: 29590},
		{Rank: 2, SpellID: 29591, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 29592, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
	},
	Pummel: shared.SpellRankTable{
		{Rank: 1, SpellID: 6552, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 20, Coef: 1}},
		{Rank: 2, SpellID: 6554, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 50, Coef: 1}},
	},
	Rend: shared.SpellRankTable{
		{Rank: 1, SpellID: 772, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 5, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 3}},
		{Rank: 2, SpellID: 6546, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 7, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 3, SpellID: 6547, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 9, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 5}},
		{Rank: 4, SpellID: 6548, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 11, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 6}},
		{Rank: 5, SpellID: 11572, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 14, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 7}},
		{Rank: 6, SpellID: 11573, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 18, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 7}},
		{Rank: 7, SpellID: 11574, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 21, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 7}},
		{Rank: 8, SpellID: 25208, Cost: 10, GCD: 1500 * time.Millisecond, MaxRange: 5, Periodic: shared.SpellRankPeriodic{Tick: 26, Coef: 0, Period: 3000 * time.Millisecond, Ticks: 7}},
	},
	Revenge: shared.SpellRankTable{
		{Rank: 1, SpellID: 6572, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 50, Max: 60, Coef: 1}},
		{Rank: 2, SpellID: 6574, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 77, Max: 93, Coef: 1}},
		{Rank: 3, SpellID: 7379, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 107, Max: 129, Coef: 1}},
		{Rank: 4, SpellID: 11600, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 180, Max: 220, Coef: 1}},
		{Rank: 5, SpellID: 11601, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 270, Max: 330, Coef: 1}},
		{Rank: 6, SpellID: 25288, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 342, Max: 418, Coef: 1}},
		{Rank: 7, SpellID: 25269, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 360, Max: 440, Coef: 1}},
		{Rank: 8, SpellID: 30357, Cost: 5, GCD: 1500 * time.Millisecond, Cooldown: 5000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 414, Max: 506, Coef: 1}},
	},
	RevengeStun: shared.SpellRankTable{
		{Rank: 1, SpellID: 12798, MaxRange: 100, Direct: shared.SpellRankFlat{Value: 100, Coef: 0}},
	},
	ShieldBash: shared.SpellRankTable{
		{Rank: 1, SpellID: 72, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 12000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 6, Coef: 1}},
		{Rank: 2, SpellID: 1671, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 12000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 18, Coef: 1}},
		{Rank: 3, SpellID: 1672, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 12000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 0}},
		{Rank: 4, SpellID: 29704, Cost: 10, GCD: 1500 * time.Millisecond, Cooldown: 12000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 63, Coef: 0}},
	},
	ShieldMastery: shared.SpellRankTable{
		{Rank: 1, SpellID: 29598, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 29599, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 3, SpellID: 29600, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
	},
	ShieldSlam: shared.SpellRankTable{
		{Rank: 1, SpellID: 23922, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 225, Max: 235, Coef: 1}},
		{Rank: 2, SpellID: 23923, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 264, Max: 276, Coef: 1}},
		{Rank: 3, SpellID: 23924, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 303, Max: 317, Coef: 1}},
		{Rank: 4, SpellID: 23925, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 342, Max: 358, Coef: 1}},
		{Rank: 5, SpellID: 25258, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 381, Max: 399, Coef: 1}},
		{Rank: 6, SpellID: 30356, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 6000 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankRange{Min: 420, Max: 440, Coef: 1}},
	},
	ShieldSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 12298},
		{Rank: 2, SpellID: 12724, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 12725, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 12726, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 12727, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	Slam: shared.SpellRankTable{
		{Rank: 1, SpellID: 1464, Cost: 15, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 32, Coef: 1}},
		{Rank: 2, SpellID: 8820, Cost: 15, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 43, Coef: 1}},
		{Rank: 3, SpellID: 11604, Cost: 15, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 68, Coef: 1}},
		{Rank: 4, SpellID: 11605, Cost: 15, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 87, Coef: 1}},
		{Rank: 5, SpellID: 25241, Cost: 15, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 105, Coef: 1}},
		{Rank: 6, SpellID: 25242, Cost: 15, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 140, Coef: 1}},
	},
	SunderArmor: shared.SpellRankTable{
		{Rank: 1, SpellID: 7386, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 2, SpellID: 7405, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 3, SpellID: 8380, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 4, SpellID: 11596, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 5, SpellID: 11597, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
		{Rank: 6, SpellID: 25225, Cost: 15, GCD: 1500 * time.Millisecond, MaxRange: 5},
	},
	SwordSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 12281},
		{Rank: 2, SpellID: 12812},
		{Rank: 3, SpellID: 12813},
		{Rank: 4, SpellID: 12814},
		{Rank: 5, SpellID: 12815},
	},
	TacticalMastery: shared.SpellRankTable{
		{Rank: 1, SpellID: 12295, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 12676, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 12677, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
	},
	ThunderClap: shared.SpellRankTable{
		{Rank: 1, SpellID: 6343, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 4000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 8198, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 4000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 23, Coef: 0}},
		{Rank: 3, SpellID: 8204, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 4000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 37, Coef: 0}},
		{Rank: 4, SpellID: 8205, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 4000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 55, Coef: 0}},
		{Rank: 5, SpellID: 11580, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 4000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 82, Coef: 0}},
		{Rank: 6, SpellID: 11581, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 4000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 103, Coef: 0}},
		{Rank: 7, SpellID: 25264, Cost: 20, GCD: 1500 * time.Millisecond, Cooldown: 4000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 123, Coef: 0}},
	},
	Toughness: shared.SpellRankTable{
		{Rank: 1, SpellID: 12299, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 12761, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 12762, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 4, SpellID: 12763, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 5, SpellID: 12764, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
	},
	TwoHandedWeaponSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 12163},
		{Rank: 2, SpellID: 12711, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 12712, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 12713, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 12714, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	VictoryRush: shared.SpellRankTable{
		{Rank: 1, SpellID: 34428, GCD: 1500 * time.Millisecond, MaxRange: 5, Direct: shared.SpellRankFlat{Value: 45, Coef: 1}},
	},
	Vitality: shared.SpellRankTable{
		{Rank: 1, SpellID: 29140, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 29143, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 29144, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
		{Rank: 4, SpellID: 29145, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 5, SpellID: 29146, Direct: shared.SpellRankFlat{Value: 5, Coef: 1}},
	},
	WeaponMastery: shared.SpellRankTable{
		{Rank: 1, SpellID: 20504},
		{Rank: 2, SpellID: 20505},
	},
}
