// Code generated by tools/database/gen_db -gen=spellranks. DO NOT EDIT.

package mage

import "github.com/wowsims/tbc/sim/common/shared"

type generatedRanks struct {
	Flamestrike shared.RankTable
}

var genRanks = generatedRanks{
	Flamestrike: shared.RankTable{
		{Rank: 1, SpellID: 2120, Cost: 195, Direct: &shared.Amount{Min: 55, Max: 71, Coef: 0.20000000298023224}, Periodic: &shared.Periodic{Tick: 12, Coef: 0.026000000536441803}},
		{Rank: 2, SpellID: 2121, Cost: 330, Direct: &shared.Amount{Min: 100, Max: 126, Coef: 0.23600000143051147}, Periodic: &shared.Periodic{Tick: 22, Coef: 0.029999999329447746}},
		{Rank: 3, SpellID: 8422, Cost: 490, Direct: &shared.Amount{Min: 159, Max: 197, Coef: 0.23600000143051147}, Periodic: &shared.Periodic{Tick: 35, Coef: 0.029999999329447746}},
		{Rank: 4, SpellID: 8423, Cost: 650, Direct: &shared.Amount{Min: 226, Max: 279, Coef: 0.23600000143051147}, Periodic: &shared.Periodic{Tick: 49, Coef: 0.029999999329447746}},
		{Rank: 5, SpellID: 10215, Cost: 815, Direct: &shared.Amount{Min: 298, Max: 367, Coef: 0.23600000143051147}, Periodic: &shared.Periodic{Tick: 66, Coef: 0.029999999329447746}},
		{Rank: 6, SpellID: 10216, Cost: 990, Direct: &shared.Amount{Min: 383, Max: 468, Coef: 0.23600000143051147}, Periodic: &shared.Periodic{Tick: 85, Coef: 0.029999999329447746}},
		{Rank: 7, SpellID: 27086, Cost: 1175, Direct: &shared.Amount{Min: 480, Max: 585, Coef: 0.23600000143051147}, Periodic: &shared.Periodic{Tick: 106, Coef: 0.029999999329447746}},
	},
}
