// Code generated by tools/database/gen_db -gen=spellranks. DO NOT EDIT.

package mage

import (
	"time"

	"github.com/wowsims/tbc/sim/common/shared"
)

// Not generated:
//   Impact: rank 1 is ambiguous between spells 11103, 12355

type generatedRanks struct {
	AmplifyMagic            shared.SpellRankTable
	ArcaneBlast             shared.SpellRankTable
	ArcaneBrilliance        shared.SpellRankTable
	ArcaneConcentration     shared.SpellRankTable
	ArcaneExplosion         shared.SpellRankTable
	ArcaneFocus             shared.SpellRankTable
	ArcaneImpact            shared.SpellRankTable
	ArcaneInstability       shared.SpellRankTable
	ArcaneIntellect         shared.SpellRankTable
	ArcaneMeditation        shared.SpellRankTable
	ArcaneMind              shared.SpellRankTable
	ArcaneMissile           shared.SpellRankTable
	ArcaneMissiles          shared.SpellRankTable
	ArcanePotency           shared.SpellRankTable
	ArcaneSubtlety          shared.SpellRankTable
	ArcticReach             shared.SpellRankTable
	ArcticWinds             shared.SpellRankTable
	BlastWave               shared.SpellRankTable
	BlazingSpeed            shared.SpellRankTable
	Blizzard                shared.SpellRankTable
	BurningSoul             shared.SpellRankTable
	Chilled                 shared.SpellRankTable
	ConeOfCold              shared.SpellRankTable
	ConjureFood             shared.SpellRankTable
	ConjureWater            shared.SpellRankTable
	CriticalMass            shared.SpellRankTable
	DampenMagic             shared.SpellRankTable
	DragonsBreath           shared.SpellRankTable
	ElementalPrecision      shared.SpellRankTable
	EmpoweredArcaneMissiles shared.SpellRankTable
	EmpoweredFireball       shared.SpellRankTable
	EmpoweredFrostbolt      shared.SpellRankTable
	FireBlast               shared.SpellRankTable
	FirePower               shared.SpellRankTable
	FireWard                shared.SpellRankTable
	Fireball                shared.SpellRankTable
	FlameThrowing           shared.SpellRankTable
	Flamestrike             shared.SpellRankTable
	FrostArmor              shared.SpellRankTable
	FrostChanneling         shared.SpellRankTable
	FrostNova               shared.SpellRankTable
	FrostWard               shared.SpellRankTable
	FrostWarding            shared.SpellRankTable
	Frostbite               shared.SpellRankTable
	Frostbolt               shared.SpellRankTable
	FrozenCore              shared.SpellRankTable
	IceArmor                shared.SpellRankTable
	IceBarrier              shared.SpellRankTable
	IceFloes                shared.SpellRankTable
	IceLance                shared.SpellRankTable
	IceShards               shared.SpellRankTable
	Ignite                  shared.SpellRankTable
	ImprovedArcaneMissiles  shared.SpellRankTable
	ImprovedBlink           shared.SpellRankTable
	ImprovedBlizzard        shared.SpellRankTable
	ImprovedConeOfCold      shared.SpellRankTable
	ImprovedCounterspell    shared.SpellRankTable
	ImprovedFireBlast       shared.SpellRankTable
	ImprovedFireball        shared.SpellRankTable
	ImprovedFlamestrike     shared.SpellRankTable
	ImprovedFrostNova       shared.SpellRankTable
	ImprovedFrostbolt       shared.SpellRankTable
	ImprovedManaShield      shared.SpellRankTable
	ImprovedScorch          shared.SpellRankTable
	Incineration            shared.SpellRankTable
	MageArmor               shared.SpellRankTable
	MagicAbsorption         shared.SpellRankTable
	MagicAttunement         shared.SpellRankTable
	ManaShield              shared.SpellRankTable
	MasterOfElements        shared.SpellRankTable
	MindMastery             shared.SpellRankTable
	MoltenArmor             shared.SpellRankTable
	MoltenFury              shared.SpellRankTable
	MoltenShields           shared.SpellRankTable
	Permafrost              shared.SpellRankTable
	PiercingIce             shared.SpellRankTable
	PlayingWithFire         shared.SpellRankTable
	Polymorph               shared.SpellRankTable
	PrismaticCloak          shared.SpellRankTable
	Pyroblast               shared.SpellRankTable
	Pyromaniac              shared.SpellRankTable
	RitualOfRefreshment     shared.SpellRankTable
	Scorch                  shared.SpellRankTable
	Shatter                 shared.SpellRankTable
	SpellPower              shared.SpellRankTable
	WandSpecialization      shared.SpellRankTable
	WintersChill            shared.SpellRankTable
}

var genRanks = generatedRanks{
	AmplifyMagic: shared.SpellRankTable{
		{Rank: 1, SpellID: 1008, Cost: 150, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 2, SpellID: 8455, Cost: 250, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 3, SpellID: 10169, Cost: 350, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 50, Coef: 0}},
		{Rank: 4, SpellID: 10170, Cost: 450, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 75, Coef: 0}},
		{Rank: 5, SpellID: 27130, Cost: 500, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 90, Coef: 0}},
		{Rank: 6, SpellID: 33946, Cost: 600, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 120, Coef: 0}},
	},
	ArcaneBlast: shared.SpellRankTable{
		{Rank: 1, SpellID: 30451, Cost: 195, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 668, Max: 772, Coef: 0.7139999866485596}},
	},
	ArcaneBrilliance: shared.SpellRankTable{
		{Rank: 1, SpellID: 23028, Cost: 1500, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 31, Coef: 0}},
		{Rank: 2, SpellID: 27127, Cost: 1800, GCD: 1500 * time.Millisecond, MaxRange: 40, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
	},
	ArcaneConcentration: shared.SpellRankTable{
		{Rank: 1, SpellID: 11213},
		{Rank: 2, SpellID: 12574},
		{Rank: 3, SpellID: 12575},
		{Rank: 4, SpellID: 12576},
		{Rank: 5, SpellID: 12577},
	},
	ArcaneExplosion: shared.SpellRankTable{
		{Rank: 1, SpellID: 1449, Cost: 75, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 34, Max: 38, Coef: 0.16599999368190765}},
		{Rank: 2, SpellID: 8437, Cost: 120, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 60, Max: 66, Coef: 0.21400000154972076}},
		{Rank: 3, SpellID: 8438, Cost: 185, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 101, Max: 110, Coef: 0.21400000154972076}},
		{Rank: 4, SpellID: 8439, Cost: 250, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 143, Max: 156, Coef: 0.21400000154972076}},
		{Rank: 5, SpellID: 10201, Cost: 315, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 191, Max: 208, Coef: 0.21400000154972076}},
		{Rank: 6, SpellID: 10202, Cost: 390, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 249, Max: 270, Coef: 0.21400000154972076}},
		{Rank: 7, SpellID: 27080, Cost: 465, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 313, Max: 338, Coef: 0.21400000154972076}},
		{Rank: 8, SpellID: 27082, Cost: 545, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankRange{Min: 377, Max: 407, Coef: 0.21400000154972076}},
	},
	ArcaneFocus: shared.SpellRankTable{
		{Rank: 1, SpellID: 11222, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 12839, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 12840, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 4, SpellID: 12841, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 5, SpellID: 12842, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
	},
	ArcaneImpact: shared.SpellRankTable{
		{Rank: 1, SpellID: 11242, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 12467, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 12469, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
	},
	ArcaneInstability: shared.SpellRankTable{
		{Rank: 1, SpellID: 15058},
		{Rank: 2, SpellID: 15059, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 3, SpellID: 15060, Direct: shared.SpellRankFlat{Value: 3, Coef: 1}},
	},
	ArcaneIntellect: shared.SpellRankTable{
		{Rank: 1, SpellID: 1459, Cost: 25, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 1460, Cost: 100, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 7, Coef: 0}},
		{Rank: 3, SpellID: 1461, Cost: 250, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 4, SpellID: 10156, Cost: 415, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 22, Coef: 0}},
		{Rank: 5, SpellID: 10157, Cost: 575, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 31, Coef: 0}},
		{Rank: 6, SpellID: 27126, Cost: 700, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
	},
	ArcaneMeditation: shared.SpellRankTable{
		{Rank: 1, SpellID: 18462, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 2, SpellID: 18463, Direct: shared.SpellRankFlat{Value: 20, Coef: 1}},
		{Rank: 3, SpellID: 18464, Direct: shared.SpellRankFlat{Value: 30, Coef: 1}},
	},
	ArcaneMind: shared.SpellRankTable{
		{Rank: 1, SpellID: 11232, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 2, SpellID: 12500, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 3, SpellID: 12501, Direct: shared.SpellRankFlat{Value: 9, Coef: 0}},
		{Rank: 4, SpellID: 12502, Direct: shared.SpellRankFlat{Value: 12, Coef: 0}},
		{Rank: 5, SpellID: 12503, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
	},
	ArcaneMissile: shared.SpellRankTable{
		{Rank: 1, SpellID: 7268, MaxRange: 30, Direct: shared.SpellRankRange{Min: 25, Max: 26, Coef: 0.15700000524520874}},
	},
	ArcaneMissiles: shared.SpellRankTable{
		{Rank: 1, SpellID: 5143, Cost: 85, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 2, SpellID: 5144, Cost: 140, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 3, SpellID: 5145, Cost: 235, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 4, SpellID: 8416, Cost: 320, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 5, SpellID: 8417, Cost: 410, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 6, SpellID: 10211, Cost: 500, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 7, SpellID: 10212, Cost: 595, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 8, SpellID: 25345, Cost: 655, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 9, SpellID: 27075, Cost: 685, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 10, SpellID: 38699, Cost: 740, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 11, SpellID: 38704, Cost: 785, GCD: 1500 * time.Millisecond, MaxRange: 30},
	},
	ArcanePotency: shared.SpellRankTable{
		{Rank: 1, SpellID: 31571, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 31572, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 3, SpellID: 31573, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
	},
	ArcaneSubtlety: shared.SpellRankTable{
		{Rank: 1, SpellID: 11210},
		{Rank: 2, SpellID: 12592},
	},
	ArcticReach: shared.SpellRankTable{
		{Rank: 1, SpellID: 16757, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 2, SpellID: 16758, Direct: shared.SpellRankFlat{Value: 20, Coef: 1}},
	},
	ArcticWinds: shared.SpellRankTable{
		{Rank: 1, SpellID: 31674},
		{Rank: 2, SpellID: 31675, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 31676, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 31677, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 31678, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	BlastWave: shared.SpellRankTable{
		{Rank: 1, SpellID: 11113, Cost: 215, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 160, Max: 192, Coef: 0.19300000369548798}},
		{Rank: 2, SpellID: 13018, Cost: 270, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 208, Max: 249, Coef: 0.19300000369548798}},
		{Rank: 3, SpellID: 13019, Cost: 355, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 285, Max: 338, Coef: 0.19300000369548798}},
		{Rank: 4, SpellID: 13020, Cost: 450, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 374, Max: 443, Coef: 0.19300000369548798}},
		{Rank: 5, SpellID: 13021, Cost: 545, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 473, Max: 556, Coef: 0.19300000369548798}},
		{Rank: 6, SpellID: 27133, Cost: 555, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 543, Max: 638, Coef: 0.19300000369548798}},
		{Rank: 7, SpellID: 33933, Cost: 620, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 616, Max: 724, Coef: 0.19300000369548798}},
	},
	BlazingSpeed: shared.SpellRankTable{
		{Rank: 1, SpellID: 31641},
		{Rank: 2, SpellID: 31642},
	},
	Blizzard: shared.SpellRankTable{
		{Rank: 1, SpellID: 10, Cost: 320, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 25, Max: 26, Coef: 0.14300000667572021}},
		{Rank: 2, SpellID: 6141, Cost: 520, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 45, Coef: 0.14300000667572021}},
		{Rank: 3, SpellID: 8427, Cost: 720, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 66, Coef: 0.14300000667572021}},
		{Rank: 4, SpellID: 10185, Cost: 935, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 91, Max: 92, Coef: 0.14300000667572021}},
		{Rank: 5, SpellID: 10186, Cost: 1160, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 118, Max: 119, Coef: 0.14300000667572021}},
		{Rank: 6, SpellID: 10187, Cost: 1400, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankFlat{Value: 151, Coef: 0.14300000667572021}},
		{Rank: 7, SpellID: 27085, Cost: 1645, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 184, Max: 185, Coef: 0.14300000667572021}},
	},
	BurningSoul: shared.SpellRankTable{
		{Rank: 1, SpellID: 11083, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
		{Rank: 2, SpellID: 12351, Direct: shared.SpellRankFlat{Value: 70, Coef: 0}},
	},
	Chilled: shared.SpellRankTable{
		{Rank: 1, SpellID: 12484, MaxRange: 50000},
		{Rank: 2, SpellID: 12485, MaxRange: 50000},
		{Rank: 3, SpellID: 12486, MaxRange: 50000},
	},
	ConeOfCold: shared.SpellRankTable{
		{Rank: 1, SpellID: 120, Cost: 210, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 102, Max: 112, Coef: 0.19300000369548798}},
		{Rank: 2, SpellID: 8492, Cost: 290, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 151, Max: 165, Coef: 0.19300000369548798}},
		{Rank: 3, SpellID: 10159, Cost: 380, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 209, Max: 229, Coef: 0.19300000369548798}},
		{Rank: 4, SpellID: 10160, Cost: 465, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 270, Max: 297, Coef: 0.19300000369548798}},
		{Rank: 5, SpellID: 10161, Cost: 555, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 342, Max: 373, Coef: 0.19300000369548798}},
		{Rank: 6, SpellID: 27087, Cost: 645, GCD: 1500 * time.Millisecond, Cooldown: 10000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 418, Max: 457, Coef: 0.19300000369548798}},
	},
	ConjureFood: shared.SpellRankTable{
		{Rank: 1, SpellID: 587, Cost: 60, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 2, SpellID: 597, Cost: 105, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 3, SpellID: 990, Cost: 180, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 4, SpellID: 6129, Cost: 285, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 5, SpellID: 10144, Cost: 420, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 6, SpellID: 10145, Cost: 585, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 7, SpellID: 28612, Cost: 650, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 8, SpellID: 33717, Cost: 885, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
	},
	ConjureWater: shared.SpellRankTable{
		{Rank: 1, SpellID: 5504, Cost: 60, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 2, SpellID: 5505, Cost: 105, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 3, SpellID: 5506, Cost: 180, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 4, SpellID: 6127, Cost: 285, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 5, SpellID: 10138, Cost: 420, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 6, SpellID: 10139, Cost: 585, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 7, SpellID: 10140, Cost: 780, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 8, SpellID: 37420, Cost: 845, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
		{Rank: 9, SpellID: 27090, Cost: 885, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond},
	},
	CriticalMass: shared.SpellRankTable{
		{Rank: 1, SpellID: 11115, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 11367, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 11368, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
	},
	DampenMagic: shared.SpellRankTable{
		{Rank: 1, SpellID: 604, Cost: 100, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 2, SpellID: 8450, Cost: 200, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 3, SpellID: 8451, Cost: 300, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 4, SpellID: 10173, Cost: 400, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 5, SpellID: 10174, Cost: 500, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 6, SpellID: 33944, Cost: 600, GCD: 1500 * time.Millisecond, MaxRange: 30},
	},
	DragonsBreath: shared.SpellRankTable{
		{Rank: 1, SpellID: 31661, Cost: 475, GCD: 1500 * time.Millisecond, Cooldown: 20000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 382, Max: 442, Coef: 0.19300000369548798}},
		{Rank: 2, SpellID: 33041, Cost: 575, GCD: 1500 * time.Millisecond, Cooldown: 20000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 463, Max: 536, Coef: 0.19300000369548798}},
		{Rank: 3, SpellID: 33042, Cost: 660, GCD: 1500 * time.Millisecond, Cooldown: 20000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 584, Max: 677, Coef: 0.19300000369548798}},
		{Rank: 4, SpellID: 33043, Cost: 700, GCD: 1500 * time.Millisecond, Cooldown: 20000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 680, Max: 790, Coef: 0.19300000369548798}},
	},
	ElementalPrecision: shared.SpellRankTable{
		{Rank: 1, SpellID: 29438},
		{Rank: 2, SpellID: 29439, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 29440, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
	},
	EmpoweredArcaneMissiles: shared.SpellRankTable{
		{Rank: 1, SpellID: 31579, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 2, SpellID: 31582, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 3, SpellID: 31583, Direct: shared.SpellRankFlat{Value: 9, Coef: 0}},
	},
	EmpoweredFireball: shared.SpellRankTable{
		{Rank: 1, SpellID: 31656, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 2, SpellID: 31657, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 3, SpellID: 31658, Direct: shared.SpellRankFlat{Value: 9, Coef: 0}},
		{Rank: 4, SpellID: 31659, Direct: shared.SpellRankFlat{Value: 12, Coef: 0}},
		{Rank: 5, SpellID: 31660, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
	},
	EmpoweredFrostbolt: shared.SpellRankTable{
		{Rank: 1, SpellID: 31682, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 31683, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 3, SpellID: 31684, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
		{Rank: 4, SpellID: 31685, Direct: shared.SpellRankFlat{Value: 8, Coef: 0}},
		{Rank: 5, SpellID: 31686, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
	},
	FireBlast: shared.SpellRankTable{
		{Rank: 1, SpellID: 2136, Cost: 40, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 27, Max: 35, Coef: 0.20399999618530273}},
		{Rank: 2, SpellID: 2137, Cost: 75, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 62, Max: 76, Coef: 0.3319999873638153}},
		{Rank: 3, SpellID: 2138, Cost: 115, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 110, Max: 134, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 8412, Cost: 165, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 177, Max: 211, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 8413, Cost: 220, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 253, Max: 301, Coef: 0.42899999022483826}},
		{Rank: 6, SpellID: 10197, Cost: 280, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 345, Max: 407, Coef: 0.42899999022483826}},
		{Rank: 7, SpellID: 10199, Cost: 340, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 446, Max: 524, Coef: 0.42899999022483826}},
		{Rank: 8, SpellID: 27078, Cost: 400, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 555, Max: 654, Coef: 0.42899999022483826}},
		{Rank: 9, SpellID: 27079, Cost: 465, GCD: 1500 * time.Millisecond, Cooldown: 8000 * time.Millisecond, MaxRange: 20, Direct: shared.SpellRankRange{Min: 664, Max: 786, Coef: 0.42899999022483826}},
	},
	FirePower: shared.SpellRankTable{
		{Rank: 1, SpellID: 11124, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 2, SpellID: 12378, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 3, SpellID: 12398, Direct: shared.SpellRankFlat{Value: 6, Coef: 1}},
		{Rank: 4, SpellID: 12399, Direct: shared.SpellRankFlat{Value: 8, Coef: 1}},
		{Rank: 5, SpellID: 12400, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
	},
	FireWard: shared.SpellRankTable{
		{Rank: 1, SpellID: 543, Cost: 85, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 165, Coef: 0}},
		{Rank: 2, SpellID: 8457, Cost: 135, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 290, Coef: 0}},
		{Rank: 3, SpellID: 8458, Cost: 195, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 470, Coef: 0}},
		{Rank: 4, SpellID: 10223, Cost: 255, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 675, Coef: 0}},
		{Rank: 5, SpellID: 10225, Cost: 320, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 875, Coef: 0}},
		{Rank: 6, SpellID: 27128, Cost: 360, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 1125, Coef: 0}},
	},
	Fireball: shared.SpellRankTable{
		{Rank: 1, SpellID: 133, Cost: 30, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 16, Max: 25, Coef: 0.12300000339746475}, Periodic: shared.SpellRankPeriodic{Tick: 1, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 2}},
		{Rank: 2, SpellID: 143, Cost: 45, CastTime: 2000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 34, Max: 49, Coef: 0.2709999978542328}, Periodic: shared.SpellRankPeriodic{Tick: 1, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 3}},
		{Rank: 3, SpellID: 145, Cost: 65, CastTime: 2500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 57, Max: 77, Coef: 0.5}, Periodic: shared.SpellRankPeriodic{Tick: 2, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 3}},
		{Rank: 4, SpellID: 3140, Cost: 95, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 89, Max: 122, Coef: 0.7929999828338623}, Periodic: shared.SpellRankPeriodic{Tick: 3, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 5, SpellID: 8400, Cost: 140, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 146, Max: 195, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 5, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 6, SpellID: 8401, Cost: 185, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 207, Max: 274, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 7, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 7, SpellID: 8402, Cost: 220, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 264, Max: 345, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 8, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 8, SpellID: 10148, Cost: 260, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 328, Max: 425, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 10, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 9, SpellID: 10149, Cost: 305, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 404, Max: 518, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 13, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 10, SpellID: 10150, Cost: 350, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 488, Max: 623, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 15, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 11, SpellID: 10151, Cost: 395, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 575, Max: 730, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 18, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 12, SpellID: 25306, Cost: 410, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 611, Max: 776, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 19, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 13, SpellID: 27070, Cost: 425, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 649, Max: 821, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 21, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 14, SpellID: 38692, Cost: 465, CastTime: 3500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 717, Max: 913, Coef: 1}, Periodic: shared.SpellRankPeriodic{Tick: 21, Coef: 0, Period: 2000 * time.Millisecond, Ticks: 4}},
	},
	FlameThrowing: shared.SpellRankTable{
		{Rank: 1, SpellID: 11100, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 2, SpellID: 12353, Direct: shared.SpellRankFlat{Value: 6, Coef: 0}},
	},
	Flamestrike: shared.SpellRankTable{
		{Rank: 1, SpellID: 2120, Cost: 195, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 55, Max: 71, Coef: 0.20000000298023224}, Periodic: shared.SpellRankPeriodic{Tick: 12, Coef: 0.026000000536441803, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 2, SpellID: 2121, Cost: 330, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 100, Max: 126, Coef: 0.23600000143051147}, Periodic: shared.SpellRankPeriodic{Tick: 22, Coef: 0.029999999329447746, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 3, SpellID: 8422, Cost: 490, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 159, Max: 197, Coef: 0.23600000143051147}, Periodic: shared.SpellRankPeriodic{Tick: 35, Coef: 0.029999999329447746, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 4, SpellID: 8423, Cost: 650, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 226, Max: 279, Coef: 0.23600000143051147}, Periodic: shared.SpellRankPeriodic{Tick: 49, Coef: 0.029999999329447746, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 5, SpellID: 10215, Cost: 815, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 298, Max: 367, Coef: 0.23600000143051147}, Periodic: shared.SpellRankPeriodic{Tick: 66, Coef: 0.029999999329447746, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 6, SpellID: 10216, Cost: 990, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 383, Max: 468, Coef: 0.23600000143051147}, Periodic: shared.SpellRankPeriodic{Tick: 85, Coef: 0.029999999329447746, Period: 2000 * time.Millisecond, Ticks: 4}},
		{Rank: 7, SpellID: 27086, Cost: 1175, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 480, Max: 585, Coef: 0.23600000143051147}, Periodic: shared.SpellRankPeriodic{Tick: 106, Coef: 0.029999999329447746, Period: 2000 * time.Millisecond, Ticks: 4}},
	},
	FrostArmor: shared.SpellRankTable{
		{Rank: 1, SpellID: 168, Cost: 60, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
		{Rank: 2, SpellID: 7300, Cost: 110, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 110, Coef: 0}},
		{Rank: 3, SpellID: 7301, Cost: 170, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 200, Coef: 0}},
	},
	FrostChanneling: shared.SpellRankTable{
		{Rank: 1, SpellID: 11160},
		{Rank: 2, SpellID: 12518},
		{Rank: 3, SpellID: 12519},
	},
	FrostNova: shared.SpellRankTable{
		{Rank: 1, SpellID: 122, Cost: 55, GCD: 1500 * time.Millisecond, Cooldown: 25000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 21, Max: 24, Coef: 0.017999999225139618}},
		{Rank: 2, SpellID: 865, Cost: 85, GCD: 1500 * time.Millisecond, Cooldown: 25000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 35, Max: 40, Coef: 0.0430000014603138}},
		{Rank: 3, SpellID: 6131, Cost: 115, GCD: 1500 * time.Millisecond, Cooldown: 25000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 54, Max: 61, Coef: 0.0430000014603138}},
		{Rank: 4, SpellID: 10230, Cost: 145, GCD: 1500 * time.Millisecond, Cooldown: 25000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 73, Max: 82, Coef: 0.0430000014603138}},
		{Rank: 5, SpellID: 27088, Cost: 185, GCD: 1500 * time.Millisecond, Cooldown: 25000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 100, Max: 113, Coef: 0.0430000014603138}},
	},
	FrostWard: shared.SpellRankTable{
		{Rank: 1, SpellID: 6143, Cost: 85, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 165, Coef: 0}},
		{Rank: 2, SpellID: 8461, Cost: 135, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 290, Coef: 0}},
		{Rank: 3, SpellID: 8462, Cost: 195, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 470, Coef: 0}},
		{Rank: 4, SpellID: 10177, Cost: 255, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 675, Coef: 0}},
		{Rank: 5, SpellID: 28609, Cost: 320, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 875, Coef: 0}},
		{Rank: 6, SpellID: 32796, Cost: 360, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 1125, Coef: 0}},
	},
	FrostWarding: shared.SpellRankTable{
		{Rank: 1, SpellID: 11189, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 2, SpellID: 28332, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
	},
	Frostbite: shared.SpellRankTable{
		{Rank: 1, SpellID: 11071, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 12496, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 12497, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
	},
	Frostbolt: shared.SpellRankTable{
		{Rank: 1, SpellID: 116, Cost: 25, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 20, Max: 22, Coef: 0.16300000250339508}},
		{Rank: 2, SpellID: 205, Cost: 35, CastTime: 1800 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 33, Max: 38, Coef: 0.26899999380111694}},
		{Rank: 3, SpellID: 837, Cost: 50, CastTime: 2200 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 54, Max: 61, Coef: 0.46299999952316284}},
		{Rank: 4, SpellID: 7322, Cost: 65, CastTime: 2600 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 78, Max: 87, Coef: 0.7059999704360962}},
		{Rank: 5, SpellID: 8406, Cost: 100, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 132, Max: 144, Coef: 0.8140000104904175}},
		{Rank: 6, SpellID: 8407, Cost: 130, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 180, Max: 197, Coef: 0.8140000104904175}},
		{Rank: 7, SpellID: 8408, Cost: 160, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 235, Max: 255, Coef: 0.8140000104904175}},
		{Rank: 8, SpellID: 10179, Cost: 195, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 301, Max: 326, Coef: 0.8140000104904175}},
		{Rank: 9, SpellID: 10180, Cost: 225, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 363, Max: 394, Coef: 0.8140000104904175}},
		{Rank: 10, SpellID: 10181, Cost: 260, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 440, Max: 475, Coef: 0.8140000104904175}},
		{Rank: 11, SpellID: 25304, Cost: 290, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 527, Max: 568, Coef: 0.8140000104904175}},
		{Rank: 12, SpellID: 27071, Cost: 300, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 548, Max: 591, Coef: 0.8140000104904175}},
		{Rank: 13, SpellID: 27072, Cost: 330, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 600, Max: 647, Coef: 0.8140000104904175}},
		{Rank: 14, SpellID: 38697, Cost: 345, CastTime: 3000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 630, Max: 680, Coef: 0.8140000104904175}},
	},
	FrozenCore: shared.SpellRankTable{
		{Rank: 1, SpellID: 31667},
		{Rank: 2, SpellID: 31668},
		{Rank: 3, SpellID: 31669},
	},
	IceArmor: shared.SpellRankTable{
		{Rank: 1, SpellID: 7302, Cost: 240, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 290, Coef: 0}},
		{Rank: 2, SpellID: 7320, Cost: 320, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 380, Coef: 0}},
		{Rank: 3, SpellID: 10219, Cost: 410, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 470, Coef: 0}},
		{Rank: 4, SpellID: 10220, Cost: 500, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 560, Coef: 0}},
		{Rank: 5, SpellID: 27124, Cost: 630, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 645, Coef: 0}},
	},
	IceBarrier: shared.SpellRankTable{
		{Rank: 1, SpellID: 11426, Cost: 305, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 454, Max: 455, Coef: 0}},
		{Rank: 2, SpellID: 13031, Cost: 360, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 568, Max: 569, Coef: 0}},
		{Rank: 3, SpellID: 13032, Cost: 420, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 699, Max: 700, Coef: 0}},
		{Rank: 4, SpellID: 13033, Cost: 480, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 842, Coef: 0}},
		{Rank: 5, SpellID: 27134, Cost: 495, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankRange{Min: 951, Max: 952, Coef: 0}},
		{Rank: 6, SpellID: 33405, Cost: 565, GCD: 1500 * time.Millisecond, Cooldown: 30000 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 1075, Coef: 0}},
	},
	IceFloes: shared.SpellRankTable{
		{Rank: 1, SpellID: 31670},
		{Rank: 2, SpellID: 31672},
	},
	IceLance: shared.SpellRankTable{
		{Rank: 1, SpellID: 30455, Cost: 150, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 173, Max: 200, Coef: 0.14300000667572021}},
	},
	IceShards: shared.SpellRankTable{
		{Rank: 1, SpellID: 11207, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 2, SpellID: 12672, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
		{Rank: 3, SpellID: 15047, Direct: shared.SpellRankFlat{Value: 60, Coef: 0}},
		{Rank: 4, SpellID: 15052, Direct: shared.SpellRankFlat{Value: 80, Coef: 0}},
		{Rank: 5, SpellID: 15053, Direct: shared.SpellRankFlat{Value: 100, Coef: 0}},
	},
	Ignite: shared.SpellRankTable{
		{Rank: 1, SpellID: 11119},
		{Rank: 2, SpellID: 11120},
		{Rank: 3, SpellID: 12846},
		{Rank: 4, SpellID: 12847},
		{Rank: 5, SpellID: 12848},
	},
	ImprovedArcaneMissiles: shared.SpellRankTable{
		{Rank: 1, SpellID: 11237, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 2, SpellID: 12463, Direct: shared.SpellRankFlat{Value: 40, Coef: 0}},
		{Rank: 3, SpellID: 12464, Direct: shared.SpellRankFlat{Value: 60, Coef: 0}},
		{Rank: 4, SpellID: 16769, Direct: shared.SpellRankFlat{Value: 80, Coef: 0}},
		{Rank: 5, SpellID: 16770, Direct: shared.SpellRankFlat{Value: 100, Coef: 0}},
	},
	ImprovedBlink: shared.SpellRankTable{
		{Rank: 1, SpellID: 31569},
		{Rank: 2, SpellID: 31570},
	},
	ImprovedBlizzard: shared.SpellRankTable{
		{Rank: 1, SpellID: 11185},
		{Rank: 2, SpellID: 12487},
		{Rank: 3, SpellID: 12488},
	},
	ImprovedConeOfCold: shared.SpellRankTable{
		{Rank: 1, SpellID: 11190, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 2, SpellID: 12489, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 3, SpellID: 12490, Direct: shared.SpellRankFlat{Value: 35, Coef: 0}},
	},
	ImprovedCounterspell: shared.SpellRankTable{
		{Rank: 1, SpellID: 11255},
		{Rank: 2, SpellID: 12598},
	},
	ImprovedFireBlast: shared.SpellRankTable{
		{Rank: 1, SpellID: 11078},
		{Rank: 2, SpellID: 11080},
		{Rank: 3, SpellID: 12342},
	},
	ImprovedFireball: shared.SpellRankTable{
		{Rank: 1, SpellID: 11069},
		{Rank: 2, SpellID: 12338},
		{Rank: 3, SpellID: 12339},
		{Rank: 4, SpellID: 12340},
		{Rank: 5, SpellID: 12341},
	},
	ImprovedFlamestrike: shared.SpellRankTable{
		{Rank: 1, SpellID: 11108, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 12349, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 12350, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
	},
	ImprovedFrostNova: shared.SpellRankTable{
		{Rank: 1, SpellID: 11165},
		{Rank: 2, SpellID: 12475},
	},
	ImprovedFrostbolt: shared.SpellRankTable{
		{Rank: 1, SpellID: 11070},
		{Rank: 2, SpellID: 12473},
		{Rank: 3, SpellID: 16763},
		{Rank: 4, SpellID: 16765},
		{Rank: 5, SpellID: 16766},
	},
	ImprovedManaShield: shared.SpellRankTable{
		{Rank: 1, SpellID: 11252},
		{Rank: 2, SpellID: 12605},
	},
	ImprovedScorch: shared.SpellRankTable{
		{Rank: 1, SpellID: 11095, Direct: shared.SpellRankFlat{Value: 33, Coef: 0}},
		{Rank: 2, SpellID: 12872, Direct: shared.SpellRankFlat{Value: 66, Coef: 0}},
		{Rank: 3, SpellID: 12873, Direct: shared.SpellRankFlat{Value: 100, Coef: 0}},
	},
	Incineration: shared.SpellRankTable{
		{Rank: 1, SpellID: 18459, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 2, SpellID: 18460, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
	},
	MageArmor: shared.SpellRankTable{
		{Rank: 1, SpellID: 6117, Cost: 270, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 22782, Cost: 380, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 22783, Cost: 490, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 4, SpellID: 27125, Cost: 575, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 18, Coef: 0}},
	},
	MagicAbsorption: shared.SpellRankTable{
		{Rank: 1, SpellID: 29441, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 2, SpellID: 29444, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 29445, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
		{Rank: 4, SpellID: 29446, Direct: shared.SpellRankFlat{Value: 4, Coef: 0}},
		{Rank: 5, SpellID: 29447, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
	},
	MagicAttunement: shared.SpellRankTable{
		{Rank: 1, SpellID: 11247, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 2, SpellID: 12606, Direct: shared.SpellRankFlat{Value: 50, Coef: 0}},
	},
	ManaShield: shared.SpellRankTable{
		{Rank: 1, SpellID: 1463, Cost: 40, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 120, Coef: 0}},
		{Rank: 2, SpellID: 8494, Cost: 60, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 210, Coef: 0}},
		{Rank: 3, SpellID: 8495, Cost: 80, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 300, Coef: 0}},
		{Rank: 4, SpellID: 10191, Cost: 100, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 390, Coef: 0}},
		{Rank: 5, SpellID: 10192, Cost: 120, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 480, Coef: 0}},
		{Rank: 6, SpellID: 10193, Cost: 140, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 570, Coef: 0}},
		{Rank: 7, SpellID: 27131, Cost: 155, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 715, Coef: 0}},
	},
	MasterOfElements: shared.SpellRankTable{
		{Rank: 1, SpellID: 29074, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 2, SpellID: 29075, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 3, SpellID: 29076, Direct: shared.SpellRankFlat{Value: 30, Coef: 0}},
	},
	MindMastery: shared.SpellRankTable{
		{Rank: 1, SpellID: 31584, Direct: shared.SpellRankFlat{Value: 5, Coef: 0}},
		{Rank: 2, SpellID: 31585, Direct: shared.SpellRankFlat{Value: 10, Coef: 0}},
		{Rank: 3, SpellID: 31586, Direct: shared.SpellRankFlat{Value: 15, Coef: 0}},
		{Rank: 4, SpellID: 31587, Direct: shared.SpellRankFlat{Value: 20, Coef: 0}},
		{Rank: 5, SpellID: 31588, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
	},
	MoltenArmor: shared.SpellRankTable{
		{Rank: 1, SpellID: 30482, Cost: 630, GCD: 1500 * time.Millisecond, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
	},
	MoltenFury: shared.SpellRankTable{
		{Rank: 1, SpellID: 31679, Direct: shared.SpellRankFlat{Value: 10, Coef: 1}},
		{Rank: 2, SpellID: 31680, Direct: shared.SpellRankFlat{Value: 20, Coef: 1}},
	},
	MoltenShields: shared.SpellRankTable{
		{Rank: 1, SpellID: 11094},
		{Rank: 2, SpellID: 13043},
	},
	Permafrost: shared.SpellRankTable{
		{Rank: 1, SpellID: 11175, Direct: shared.SpellRankFlat{Value: 1000, Coef: 0}},
		{Rank: 2, SpellID: 12569, Direct: shared.SpellRankFlat{Value: 2000, Coef: 0}},
		{Rank: 3, SpellID: 12571, Direct: shared.SpellRankFlat{Value: 3000, Coef: 0}},
	},
	PiercingIce: shared.SpellRankTable{
		{Rank: 1, SpellID: 11151, Direct: shared.SpellRankFlat{Value: 2, Coef: 1}},
		{Rank: 2, SpellID: 12952, Direct: shared.SpellRankFlat{Value: 4, Coef: 1}},
		{Rank: 3, SpellID: 12953, Direct: shared.SpellRankFlat{Value: 6, Coef: 1}},
	},
	PlayingWithFire: shared.SpellRankTable{
		{Rank: 1, SpellID: 31638},
		{Rank: 2, SpellID: 31639, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 31640, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
	},
	Polymorph: shared.SpellRankTable{
		{Rank: 1, SpellID: 118, Cost: 60, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 2, SpellID: 12824, Cost: 90, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 3, SpellID: 12825, Cost: 120, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
		{Rank: 4, SpellID: 12826, Cost: 150, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30},
	},
	PrismaticCloak: shared.SpellRankTable{
		{Rank: 1, SpellID: 31574},
		{Rank: 2, SpellID: 31575},
	},
	Pyroblast: shared.SpellRankTable{
		{Rank: 1, SpellID: 11366, Cost: 125, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 148, Max: 195, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 14, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 2, SpellID: 12505, Cost: 150, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 193, Max: 250, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 18, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 3, SpellID: 12522, Cost: 195, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 270, Max: 343, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 24, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 4, SpellID: 12523, Cost: 240, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 347, Max: 437, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 31, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 5, SpellID: 12524, Cost: 285, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 427, Max: 536, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 39, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 6, SpellID: 12525, Cost: 335, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 525, Max: 654, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 47, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 7, SpellID: 12526, Cost: 385, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 625, Max: 776, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 57, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 8, SpellID: 18809, Cost: 440, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 735, Max: 926, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 67, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 9, SpellID: 27132, Cost: 460, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 866, Max: 1094, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 78, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
		{Rank: 10, SpellID: 33938, Cost: 500, CastTime: 6000 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 35, Direct: shared.SpellRankRange{Min: 939, Max: 1191, Coef: 1.149999976158142}, Periodic: shared.SpellRankPeriodic{Tick: 89, Coef: 0.05000000074505806, Period: 3000 * time.Millisecond, Ticks: 4}},
	},
	Pyromaniac: shared.SpellRankTable{
		{Rank: 1, SpellID: 34293},
		{Rank: 2, SpellID: 34295, Direct: shared.SpellRankFlat{Value: 2, Coef: 0}},
		{Rank: 3, SpellID: 34296, Direct: shared.SpellRankFlat{Value: 3, Coef: 0}},
	},
	RitualOfRefreshment: shared.SpellRankTable{
		{Rank: 1, SpellID: 43987, GCD: 1500 * time.Millisecond, Cooldown: 300000 * time.Millisecond, MaxRange: 30},
	},
	Scorch: shared.SpellRankTable{
		{Rank: 1, SpellID: 2948, Cost: 50, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 56, Max: 69, Coef: 0.42899999022483826}},
		{Rank: 2, SpellID: 8444, Cost: 65, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 81, Max: 98, Coef: 0.42899999022483826}},
		{Rank: 3, SpellID: 8445, Cost: 80, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 105, Max: 126, Coef: 0.42899999022483826}},
		{Rank: 4, SpellID: 8446, Cost: 100, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 139, Max: 165, Coef: 0.42899999022483826}},
		{Rank: 5, SpellID: 10205, Cost: 115, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 168, Max: 199, Coef: 0.42899999022483826}},
		{Rank: 6, SpellID: 10206, Cost: 135, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 207, Max: 247, Coef: 0.42899999022483826}},
		{Rank: 7, SpellID: 10207, Cost: 150, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 241, Max: 284, Coef: 0.42899999022483826}},
		{Rank: 8, SpellID: 27073, Cost: 165, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 278, Max: 327, Coef: 0.42899999022483826}},
		{Rank: 9, SpellID: 27074, Cost: 180, CastTime: 1500 * time.Millisecond, GCD: 1500 * time.Millisecond, MaxRange: 30, Direct: shared.SpellRankRange{Min: 305, Max: 361, Coef: 0.42899999022483826}},
	},
	Shatter: shared.SpellRankTable{
		{Rank: 1, SpellID: 11170},
		{Rank: 2, SpellID: 12982},
		{Rank: 3, SpellID: 12983},
		{Rank: 4, SpellID: 12984},
		{Rank: 5, SpellID: 12985},
	},
	SpellPower: shared.SpellRankTable{
		{Rank: 1, SpellID: 35578, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
		{Rank: 2, SpellID: 35581, Direct: shared.SpellRankFlat{Value: 50, Coef: 0}},
	},
	WandSpecialization: shared.SpellRankTable{
		{Rank: 1, SpellID: 6057, Direct: shared.SpellRankFlat{Value: 13, Coef: 0}},
		{Rank: 2, SpellID: 6085, Direct: shared.SpellRankFlat{Value: 25, Coef: 0}},
	},
	WintersChill: shared.SpellRankTable{
		{Rank: 1, SpellID: 11180},
		{Rank: 2, SpellID: 28592},
		{Rank: 3, SpellID: 28593},
		{Rank: 4, SpellID: 28594},
		{Rank: 5, SpellID: 28595},
	},
}
