// Code generated by tools/database/gen_db -gen=spellranks. DO NOT EDIT.

package druid

import "github.com/wowsims/tbc/sim/common/shared"

type generatedRanks struct {
	Starfire shared.RankTable
}

var genRanks = generatedRanks{
	Starfire: shared.RankTable{
		{Rank: 1, SpellID: 2912, Cost: 95, Direct: &shared.Amount{Min: 95, Max: 115, Coef: 1}},
		{Rank: 2, SpellID: 8949, Cost: 135, Direct: &shared.Amount{Min: 146, Max: 177, Coef: 1}},
		{Rank: 3, SpellID: 8950, Cost: 180, Direct: &shared.Amount{Min: 212, Max: 253, Coef: 1}},
		{Rank: 4, SpellID: 8951, Cost: 230, Direct: &shared.Amount{Min: 293, Max: 348, Coef: 1}},
		{Rank: 5, SpellID: 9875, Cost: 275, Direct: &shared.Amount{Min: 378, Max: 445, Coef: 1}},
		{Rank: 6, SpellID: 9876, Cost: 315, Direct: &shared.Amount{Min: 463, Max: 543, Coef: 1}},
		{Rank: 7, SpellID: 25298, Cost: 340, Direct: &shared.Amount{Min: 514, Max: 603, Coef: 1}},
		{Rank: 8, SpellID: 26986, Cost: 370, Direct: &shared.Amount{Min: 550, Max: 647, Coef: 1}},
	},
}
