// Code generated by tools/database/gen_db/gen_character_constants_ts.go. DO NOT EDIT.

import { ArmorType, Class, Race, RangedWeaponType, Spec, WeaponType } from '../proto/common';

export type EligibleWeaponType = {
	weaponType: WeaponType;
	canUseTwoHand: boolean;
};

export const CLASS_ARMOR_TYPES: Record<number, ArmorType[]> = {
	[Class.ClassWarrior]: [ArmorType.ArmorTypePlate, ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassPaladin]: [ArmorType.ArmorTypePlate, ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassHunter]: [ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassRogue]: [ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassPriest]: [ArmorType.ArmorTypeCloth],
	[Class.ClassShaman]: [ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassMage]: [ArmorType.ArmorTypeCloth],
	[Class.ClassWarlock]: [ArmorType.ArmorTypeCloth],
	[Class.ClassDruid]: [ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
};

export const CLASS_WEAPON_TYPES: Record<number, EligibleWeaponType[]> = {
	[Class.ClassWarrior]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeShield, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: true }],
	[Class.ClassPaladin]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeShield, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: true }],
	[Class.ClassHunter]: [],
	[Class.ClassRogue]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: false }],
	[Class.ClassPriest]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }],
	[Class.ClassShaman]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeShield, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }],
	[Class.ClassMage]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: false }],
	[Class.ClassWarlock]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: false }],
	[Class.ClassDruid]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }],
};

export const CLASS_RANGED_WEAPON_TYPES: Record<number, RangedWeaponType[]> = {
	[Class.ClassWarrior]: [RangedWeaponType.RangedWeaponTypeBow, RangedWeaponType.RangedWeaponTypeCrossbow, RangedWeaponType.RangedWeaponTypeGun, RangedWeaponType.RangedWeaponTypeThrown],
	[Class.ClassPaladin]: [RangedWeaponType.RangedWeaponTypeLibram],
	[Class.ClassHunter]: [RangedWeaponType.RangedWeaponTypeBow, RangedWeaponType.RangedWeaponTypeCrossbow, RangedWeaponType.RangedWeaponTypeGun],
	[Class.ClassRogue]: [RangedWeaponType.RangedWeaponTypeBow, RangedWeaponType.RangedWeaponTypeCrossbow, RangedWeaponType.RangedWeaponTypeGun, RangedWeaponType.RangedWeaponTypeThrown],
	[Class.ClassPriest]: [RangedWeaponType.RangedWeaponTypeWand],
	[Class.ClassShaman]: [RangedWeaponType.RangedWeaponTypeTotem],
	[Class.ClassMage]: [RangedWeaponType.RangedWeaponTypeWand],
	[Class.ClassWarlock]: [RangedWeaponType.RangedWeaponTypeWand],
	[Class.ClassDruid]: [RangedWeaponType.RangedWeaponTypeIdol],
};

export const CLASS_RACES: Record<number, Race[]> = {
	[Class.ClassWarrior]: [Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceGnome, Race.RaceDraenei, Race.RaceOrc, Race.RaceUndead, Race.RaceTauren, Race.RaceTroll],
	[Class.ClassPaladin]: [Race.RaceHuman, Race.RaceDwarf, Race.RaceDraenei, Race.RaceBloodElf],
	[Class.ClassHunter]: [Race.RaceDwarf, Race.RaceNightElf, Race.RaceDraenei, Race.RaceOrc, Race.RaceTauren, Race.RaceTroll, Race.RaceBloodElf],
	[Class.ClassRogue]: [Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceGnome, Race.RaceOrc, Race.RaceUndead, Race.RaceTroll, Race.RaceBloodElf],
	[Class.ClassPriest]: [Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceDraenei, Race.RaceUndead, Race.RaceTroll, Race.RaceBloodElf],
	[Class.ClassShaman]: [Race.RaceDraenei, Race.RaceOrc, Race.RaceTauren, Race.RaceTroll],
	[Class.ClassMage]: [Race.RaceHuman, Race.RaceGnome, Race.RaceDraenei, Race.RaceUndead, Race.RaceTroll, Race.RaceBloodElf],
	[Class.ClassWarlock]: [Race.RaceHuman, Race.RaceGnome, Race.RaceOrc, Race.RaceUndead, Race.RaceBloodElf],
	[Class.ClassDruid]: [Race.RaceNightElf, Race.RaceTauren],
};

export const SPEC_CAN_DUAL_WIELD = new Set<Spec>([
	Spec.SpecHunter,
	Spec.SpecRogue,
	Spec.SpecEnhancementShaman,
	Spec.SpecDpsWarrior,
	Spec.SpecProtectionWarrior,
]);
